import type { ScoreDefinition } from './biology-score-types.js';

// biology-score-tier2-definitions.js — contextual Biology Score definitions for recovery and immune patterning.

export const TIER2_BIOLOGY_SCORE_DEFINITIONS = [
  {
    id: 'immuneCellBalance', title: 'Immune Cell Balance', kicker: 'CBC differential pattern', evidence: 'contextual', panelTier: 'minimum', coherenceDomain: 'immune', coherenceWeight: 1.0,
    summary: 'White-cell count and differential pattern for immune activation, suppression, allergy/eosinophil, and stress-skew context.',
    inputs: [
      { key: 'wbc', label: 'White blood cells', weight: 1.25, paths: 'hematology.wbc', core: true },
      { key: 'neutrophils', label: 'Neutrophils', weight: 1.1, paths: 'differential.neutrophils', core: true },
      { key: 'lymphocytes', label: 'Lymphocytes', weight: 1.1, paths: 'differential.lymphocytes', core: true },
      { key: 'monocytes', label: 'Monocytes', weight: 0.55, paths: 'differential.monocytes' },
      { key: 'eosinophils', label: 'Eosinophils', weight: 0.45, paths: 'differential.eosinophils' },
      { key: 'basophils', label: 'Basophils', weight: 0.25, paths: 'differential.basophils' },
      { key: 'nlr', label: 'Neutrophil/lymphocyte ratio', weight: 0.75, paths: 'calculatedRatios.nlr' },
      { key: 'platelets', label: 'Platelets', weight: 0.35, paths: 'hematology.platelets' },
      { key: 'hsCrp', label: 'hs-CRP', weight: 0.45, paths: 'proteins.hsCRP' },
      { key: 'vitaminD', label: '25-OH vitamin D', weight: 0.25, paths: 'vitamins.vitaminD' },
    ],
  },
  {
    id: 'anabolicRecoverySignal', title: 'Recovery Context', kicker: 'Hormone and protein pattern', evidence: 'contextual', panelTier: 'minimum', coherenceDomain: 'recovery', coherenceWeight: 0.8,
    summary: 'Hormone, protein, inflammation, thyroid, and tissue-stress context for recovery and anabolic/catabolic balance.',
    inputs: [
      { key: 'testosterone', label: 'Total testosterone', weight: 1.05, paths: 'hormones.testosterone', sexWeightScale: { female: 0.35 }, core: true },
      { key: 'freeTestosterone', label: 'Free testosterone', weight: 1.25, paths: 'hormones.freeTestosterone', sexWeightScale: { female: 0.35 }, core: true },
      { key: 'shbg', label: 'SHBG', weight: 0.55, paths: 'hormones.shbg' },
      { key: 'fai', label: 'Free androgen index', weight: 0.65, paths: 'hormones.fai', sexWeightScale: { female: 0.35 } },
      { key: 'dheaS', label: 'DHEA-S', weight: 0.75, paths: 'hormones.dheaS' },
      { key: 'igf1', label: 'IGF-1', weight: 0.8, paths: 'hormones.igf1' },
      { key: 'estradiol', label: 'Estradiol', weight: 0.4, paths: 'hormones.estradiol', sexWeightScale: { female: 1.7 } },
      { key: 'lh', label: 'LH', weight: 0.25, paths: 'hormones.lh' },
      { key: 'fsh', label: 'FSH', weight: 0.25, paths: 'hormones.fsh' },
      { key: 'albumin', label: 'Albumin', weight: 0.85, paths: 'proteins.albumin', core: true },
      { key: 'totalProtein', label: 'Total protein', weight: 0.65, paths: 'proteins.totalProtein', core: true },
      { key: 'hemoglobin', label: 'Hemoglobin', weight: 0.45, paths: 'hematology.hemoglobin' },
      { key: 'hsCrp', label: 'hs-CRP', weight: 0.55, paths: 'proteins.hsCRP' },
      { key: 'vitaminD', label: '25-OH vitamin D', weight: 0.35, paths: 'vitamins.vitaminD' },
      { key: 'ft3', label: 'Free T3', weight: 0.3, paths: 'thyroid.ft3' },
      { key: 'tsh', label: 'TSH', weight: 0.25, paths: 'thyroid.tsh' },
      { key: 'ck', label: 'Creatine kinase', weight: 0.35, paths: 'biochemistry.creatineKinase' },
      { key: 'urea', label: 'Urea', weight: 0.25, paths: 'biochemistry.urea' },
      { key: 'creatinine', label: 'Creatinine', weight: 0.25, paths: 'biochemistry.creatinine' },
    ],
  },
  {
    id: 'cellularEnergyCoherence', title: 'Cellular Energy', kicker: 'Organic-acid pattern', evidence: 'experimental', panelTier: 'extended', coherenceDomain: 'energy', coherenceWeight: 1.0,
    summary: 'Advanced mitochondrial-energy pattern using organic acids, fatty-acid oxidation clues, CoQ10/carnitine context, and basic bloodwork stress signals when available.',
    inputs: [
      { key: 'lactate', label: 'Lactate / lactic acid', weight: 1.25, paths: 'oatMetabolic.lactic' },
      { key: 'pyruvate', label: 'Pyruvate / pyruvic acid', weight: 1.1, paths: 'oatMetabolic.pyruvic' },
      { key: 'bloodLactate', label: 'Blood lactate', weight: 1.25, paths: 'biochemistry.lactate' },
      { key: 'bloodPyruvate', label: 'Blood pyruvate', weight: 1.1, paths: 'biochemistry.pyruvate' },
      { key: 'succinate', label: 'Succinate', weight: 0.85, paths: 'oatMetabolic.succinic' },
      { key: 'fumarate', label: 'Fumarate', weight: 0.75, paths: 'oatMetabolic.fumaric' },
      { key: 'malate', label: 'Malate', weight: 0.75, paths: 'oatMetabolic.malic' },
      { key: 'oxoglutarate', label: '2-oxoglutarate', weight: 0.65, paths: 'oatMetabolic.oxoglutaric2' },
      { key: 'aconitate', label: 'Aconitate', weight: 0.55, paths: 'oatMetabolic.aconitic' },
      { key: 'methylglutaconic', label: '3-methylglutaconic acid', weight: 0.65, paths: 'oatMetabolic.methylglutaconic3' },
      { key: 'ethylmalonic', label: 'Ethylmalonic acid', weight: 0.75, paths: 'oatAminoFatty.ethylmalonic' },
      { key: 'methylsuccinic', label: 'Methylsuccinic acid', weight: 0.55, paths: 'oatAminoFatty.methylsuccinic' },
      { key: 'adipic', label: 'Adipic acid', weight: 0.45, paths: 'oatAminoFatty.adipic' },
      { key: 'suberic', label: 'Suberic acid', weight: 0.45, paths: 'oatAminoFatty.suberic' },
      { key: 'sebacic', label: 'Sebacic acid', weight: 0.45, paths: 'oatAminoFatty.sebacic' },
      { key: 'coq10Need', label: 'HMG', weight: 0.6, paths: 'oatNutritional.hmg' },
      { key: 'carnitine', label: 'Carnitine', weight: 0.55, paths: 'biostarksAmino.carnitine' },
      { key: 'ck', label: 'Creatine kinase', weight: 0.35, paths: 'biochemistry.creatineKinase' },
      { key: 'ft3', label: 'Free T3', weight: 0.3, paths: 'thyroid.ft3' },
    ],
  },
  {
    id: 'stressResilience', title: 'Stress Hormone Context', kicker: 'Timed cortisol and DHEA-S', evidence: 'contextual', panelTier: 'extended', coherenceDomain: 'stress', coherenceWeight: 0.9,
    summary: 'Timed cortisol and DHEA-S form the core stress-hormone pattern. Glucose, inflammation and thyroid markers add context.',
    inputs: [
      { key: 'cortisol', label: 'Cortisol', weight: 1.35, paths: ['hormones.cortisol', 'biostarksHormone.cortisol'] },
      { key: 'dheaS', label: 'DHEA-S', weight: 0.95, paths: 'hormones.dheaS' },
      { key: 'testCortisolRatio', label: 'Testosterone/cortisol ratio', weight: 0.8, paths: 'biostarksHormone.testCortisolRatio' },
      { key: 'glucose', label: 'Fasting glucose', weight: 0.45, paths: 'biochemistry.glucose' },
      { key: 'insulin', label: 'Insulin', weight: 0.45, paths: 'diabetes.insulin' },
      { key: 'hsCrp', label: 'hs-CRP', weight: 0.55, paths: 'proteins.hsCRP' },
      { key: 'wbc', label: 'WBC', weight: 0.35, paths: 'hematology.wbc' },
      { key: 'neutrophils', label: 'Neutrophils', weight: 0.35, paths: 'differential.neutrophils' },
      { key: 'lymphocytes', label: 'Lymphocytes', weight: 0.35, paths: 'differential.lymphocytes' },
      { key: 'ft3', label: 'Free T3', weight: 0.35, paths: 'thyroid.ft3' },
      { key: 'tsh', label: 'TSH', weight: 0.25, paths: 'thyroid.tsh' },
    ],
  },
  {
    id: 'hormoneAxis', title: 'Hormone Axis', kicker: 'Sex + pituitary signaling', evidence: 'contextual', panelTier: 'minimum', coherenceDomain: 'hormones', coherenceWeight: 0.9,
    summary: 'Sex-hormone and pituitary-axis coherence. Interpreted with sex, age, cycle state, menopause, contraception, and hormone-therapy context.',
    inputs: [
      { key: 'testosterone', label: 'Total testosterone', weight: 1.0, paths: 'hormones.testosterone', sexWeightScale: { female: 0.45 }, core: true, coreSex: ['male'], coreGroup: 'maleAndrogenStatus', coreGroupLabel: 'Male androgen status (total or free testosterone)' },
      { key: 'freeTestosterone', label: 'Free testosterone', weight: 1.1, paths: 'hormones.freeTestosterone', sexWeightScale: { female: 0.45 }, core: true, coreSex: ['male'], coreGroup: 'maleAndrogenStatus', coreGroupLabel: 'Male androgen status (total or free testosterone)' },
      { key: 'shbg', label: 'SHBG', weight: 0.65, paths: 'hormones.shbg', core: true },
      { key: 'estradiol', label: 'Estradiol', weight: 0.9, paths: 'hormones.estradiol', sexWeightScale: { male: 0.65, female: 1.25 }, core: true, coreSex: ['female'], coreGroup: 'femaleSexHormoneStatus', coreGroupLabel: 'Female sex hormone status (estradiol or progesterone)' },
      { key: 'progesterone', label: 'Progesterone', weight: 0.75, paths: 'hormones.progesterone', sexWeightScale: { male: 0.35, female: 1.4 }, core: true, coreSex: ['female'], coreGroup: 'femaleSexHormoneStatus', coreGroupLabel: 'Female sex hormone status (estradiol or progesterone)' },
      { key: 'lh', label: 'LH', weight: 0.65, paths: 'hormones.lh', core: true },
      { key: 'fsh', label: 'FSH', weight: 0.65, paths: 'hormones.fsh', core: true },
      { key: 'prolactin', label: 'Prolactin', weight: 0.6, paths: 'hormones.prolactin', core: true },
      { key: 'dht', label: 'DHT', weight: 0.45, paths: ['hormones.dht', 'hormones.dihydrotestosterone', 'custom.dht', 'custom.dihydrotestosterone'] },
      { key: 'androstenedione', label: 'Androstenedione', weight: 0.35, paths: ['hormones.androstenedione', 'custom.androstenedione'] },
      { key: 'dheaS', label: 'DHEA-S', weight: 0.55, paths: 'hormones.dheaS' },
      { key: 'cortisol', label: 'Cortisol', weight: 0.35, paths: ['hormones.cortisol', 'biostarksHormone.cortisol'] },
    ],
  },
  {
    id: 'gutImmuneSignal', title: 'Gut–Immune Signal', kicker: 'Stool and microbial-metabolite clues', evidence: 'experimental', panelTier: 'extended', coherenceDomain: 'gut', coherenceWeight: 0.75,
    summary: 'Explore stool and microbial-metabolite findings alongside inflammation and nutrient context. Read each assay on its own terms.',
    inputs: [
      { key: 'calprotectin', label: 'Calprotectin', weight: 1.2, paths: ['stool.calprotectin', 'gut.calprotectin'] },
      { key: 'zonulin', label: 'Zonulin assay', weight: 0.75, paths: ['stool.zonulin', 'gut.zonulin'] },
      { key: 'secretoryIga', label: 'Secretory IgA', weight: 0.7, paths: ['stool.secretoryIgA', 'gut.secretoryIgA'] },
      { key: 'arabinose', label: 'Urine arabinose', weight: 0.7, paths: 'oatMicrobial.arabinose' },
      { key: 'hphpa', label: 'HPHPA microbial marker', weight: 0.65, paths: 'oatMicrobial.hphpa' },
      { key: 'cresol4', label: '4-cresol microbial marker', weight: 0.55, paths: 'oatMicrobial.cresol4' },
      { key: 'dArabinitol', label: 'Urine D-arabinitol', weight: 0.55, paths: 'oatMicrobial.dArabinitol' },
      { key: 'hsCrp', label: 'hs-CRP', weight: 0.55, paths: 'proteins.hsCRP' },
      { key: 'eosinophils', label: 'Eosinophils', weight: 0.45, paths: 'differential.eosinophils' },
      { key: 'albumin', label: 'Albumin', weight: 0.35, paths: 'proteins.albumin' },
      { key: 'b12', label: 'Vitamin B12', weight: 0.3, paths: ['vitamins.activeB12', 'vitamins.vitaminB12'] },
    ],
  },
  {
    id: 'nerveMuscleSignal', title: 'Nerve–Muscle Signal', kicker: 'Neuromuscular context', evidence: 'experimental', panelTier: 'extended', coherenceDomain: 'neuromuscular', coherenceWeight: 0.75,
    summary: 'Neuromuscular stress and support pattern from CK, muscle mass proxies, B12/methylation, glucose exposure, inflammation, magnesium, and advanced nerve markers when available.',
    inputs: [
      { key: 'ck', label: 'Creatine kinase', weight: 0.95, paths: 'biochemistry.creatineKinase' },
      { key: 'creatinine', label: 'Creatinine', weight: 0.55, paths: 'biochemistry.creatinine' },
      { key: 'activeB12', label: 'Active B12', weight: 0.75, paths: ['vitamins.activeB12', 'vitamins.holotranscobalamin', 'custom.activeB12'] },
      { key: 'b12', label: 'Total B12', weight: 0.55, paths: 'vitamins.vitaminB12' },
      { key: 'homocysteine', label: 'Homocysteine', weight: 0.75, paths: 'coagulation.homocysteine' },
      { key: 'vitaminD', label: '25-OH vitamin D', weight: 0.45, paths: 'vitamins.vitaminD' },
      { key: 'magnesium', label: 'Magnesium', weight: 0.45, paths: 'electrolytes.magnesium' },
      { key: 'hba1c', label: 'HbA1c', weight: 0.55, paths: 'diabetes.hba1c' },
      { key: 'glucose', label: 'Glucose', weight: 0.35, paths: 'biochemistry.glucose' },
      { key: 'hsCrp', label: 'hs-CRP', weight: 0.4, paths: 'proteins.hsCRP' },
      { key: 'magnesiumRBC', label: 'RBC magnesium', weight: 0.45, paths: ['electrolytes.magnesiumRBC', 'biostarksMineral.magnesium'] },
      { key: 'mma', label: 'Serum methylmalonic acid', weight: 0.5, paths: ['vitamins.methylmalonicAcid', 'vitamins.mma'] },
      { key: 'bloodLactate', label: 'Blood lactate', weight: 0.35, paths: 'biochemistry.lactate' },
      { key: 'nfl', label: 'Neurofilament light', weight: 1.25, paths: ['proteins.neurofilamentLight', 'neurology.neurofilamentLight', 'neurology.nfl'] },
      { key: 'lactate', label: 'Lactate', weight: 0.35, paths: 'oatMetabolic.lactic' },
    ],
  },
] satisfies ScoreDefinition[];
