// dna-file-detection.js - lightweight DNA file classification shared by lazy import flows.

// Detect DNA file by checking the first few lines of text content.
export function detectDNAFile(text: unknown) {
  const first = String(text || '').slice(0, 1500);
  if (first.startsWith('#AncestryDNA')) return 'ancestry';
  // MyHeritage's Low-pass WGS export (2025+ format) prepends a
  // ##fileformat=MyHeritage comment block before the column header.
  if (/^##fileformat=MyHeritage/im.test(first)) return 'csv';
  if (first.includes('generated by 23andMe')) {
    // 23andMe Mito/Y files share the normal header, so inspect data rows.
    const dataLines = first
      .split(/\r?\n/)
      .filter(line => line.trim() && !line.startsWith('#') && (line.match(/\t/g) || []).length >= 3);
    if (dataLines.length > 0 && dataLines.every(line => /^\S+\tMT\t/.test(line))) return '23andme-mito';
    if (dataLines.length > 0 && dataLines.every(line => /^\S+\tY\t/.test(line))) return '23andme-y';
    return '23andme';
  }
  if (first.includes('# Living DNA customer genotype data download file version')) {
    // Living DNA offers separate autosomal and motherline downloads. The
    // motherline file contains only positive mtDNA markers such as "263G".
    const livingDataLines = first
      .split(/\r?\n/)
      .map(line => line.trim())
      .filter(line => line && !line.startsWith('#'));
    if (livingDataLines.length > 0 && livingDataLines.every(line => /^\d+[ACGT]$/i.test(line))) return 'mtdna';
    return 'livingdna';
  }
  if (first.includes('GSGT Version,')) return 'illumina-gsgt';

  const firstNonComment = first
    .split(/\r?\n/)
    .find(line => line.trim() && !line.startsWith('#'))
    ?.replace(/^\uFEFF/, '')
    .trim() || '';
  const compactHeader = firstNonComment.replace(/\s+/g, '');
  if (/^"?rsid"?,"?gene"?,"?category"?,"?genotype"?,"?zygosity"?,"?risk_?allele"?,"?result"?/i.test(compactHeader)) {
    return 'annotated-snp-report';
  }
  if (/^RSID,CHROMOSOME,POSITION,RESULT$/i.test(firstNonComment)) return 'csv';
  if (/^"?RSID"?,/i.test(firstNonComment)) return 'csv';
  if (/^rsid\tchromosome\tposition\tgenotype/i.test(firstNonComment)) return '23andme';

  const dataLines = first.split(/\r?\n/).filter(line => line.trim() && !line.startsWith('#'));
  if (dataLines.length > 0 && /^rs\d+\t\d+\t\d+\t[ACGT\-]{1,2}$/i.test(dataLines[0]!.trim())) return '23andme';
  if (
    dataLines.length > 0
    && dataLines.length < 200
    && dataLines.filter(line => /^\d+[ACGT]$/i.test(line.trim())).length >= dataLines.length * 0.8
  ) {
    return 'mtdna';
  }
  return null;
}

// Check if a dropped/selected file looks like a DNA raw data file by name.
export function isDNAFile(file: { readonly name?: unknown } | null | undefined) {
  if (!file) return false;
  const name = String(file.name || '').toLowerCase();
  if (name.includes('ancestrydna')) return true;
  if (name.includes('23andme')) return true;
  if (name.includes('myheritage') && name.includes('dna')) return true;
  if (name.includes('family_finder')) return true;
  if (name.includes('livingdna') || name.includes('living_dna')) return true;
  if (name.includes('genome') || name.includes('genotype') || name.includes('raw_dna') || name.includes('rawdna')) return true;
  if (name.includes('mtdna') || name.includes('mt-dna') || name.includes('mt_dna')) return true;
  if (name.includes('dnaera')) return true;
  return false;
}

// Content-based DNA detection reads only the first 1500 bytes.
export async function isDNAFileByContent(file: Pick<Blob, 'slice'>) {
  try {
    const header = await file.slice(0, 1500).text();
    return detectDNAFile(header) !== null;
  } catch {
    return false;
  }
}
