import type { JSONDetached } from './export-report.js';
import type { ReportDataSnapshot, ReportOptions, ReportResult } from './export-report-data.js';

export interface ConciseReportOptions extends Omit<Pick<ReportOptions,
  'sections' | 'appendixSections' | 'genomeMode' | 'genomeVariants' | 'presetLabel' | 'purpose'>, 'sections'> {
  sections: string[];
  rangeMode?: string;
  aiSummary?: { text?: unknown } | null;
}
export interface ReportHeaderFact { label: string; value?: unknown }

// Summary-first report body. Values are escaped at the last rendering boundary.
import { escapeHTML, escapeAttr, formatValue, getStatus } from './utils.js';
import { getSupplementDosageParts, selectReportGenomeFindings } from './export-report-data.js';
import { getSupplementStatus, getSupplementPeriods } from './supplement-medication-domain.js';
const esc = (value: unknown) => escapeHTML(String(value ?? ''));
const cell = (value: unknown) => esc(value).replace(/\n/g, '<br>');
const table = (columns: readonly unknown[], rows: readonly (readonly unknown[])[], className = '', statuses: readonly string[] = []) => `<table class="${className}"><thead><tr>${columns.map(label => `<th>${esc(label)}</th>`).join('')}</tr></thead><tbody>${rows.map((row, rowIndex) => `<tr>${row.map((value, index) => `<td${index === row.length - 1 && statuses[rowIndex] ? ` class="val-${['high', 'low', 'normal'].includes(statuses[rowIndex]!) ? statuses[rowIndex] : 'unrated'}"` : ''}>${cell(value)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const bounds = (range: ReportResult['ranges']['displayed'][number] | null | undefined) => range?.min == null && range?.max == null ? 'not set' : range.min == null ? `≤${formatValue(range.max)}` : range.max == null ? `≥${formatValue(range.min)}` : `${formatValue(range.min)}–${formatValue(range.max)}`;
const excerpt = (value: unknown, limit = 360) => { const text = String(value || ''); return text.length > limit ? text.slice(0, limit) + '… [excerpt]' : text; };
export function reportReference(reference: unknown) {
  try {
    const url = new URL(String(reference));
    if (!['https:', 'http:'].includes(url.protocol)) return esc(reference);
    const pubmed = url.hostname === 'pubmed.ncbi.nlm.nih.gov' && url.pathname.match(/^\/(\d+)\/?$/)?.[1];
    return `<a href="${escapeAttr(url.href)}" target="_blank" rel="noopener noreferrer">${esc(pubmed ? `PubMed ${pubmed}` : url.hostname + url.pathname)}</a>`;
  } catch { return esc(reference); }
}

/** Visible in the preview and print; this is not a claim of interoperable provenance. */
export function renderReportOriginNotice(summary: ConciseReportOptions['aiSummary']) {
  return summary?.text ? `<aside class="report-origin-notice" aria-label="AI origin disclosure"><strong>AI-assisted report · Contains an AI-generated overview</strong><p>The opening overview was generated by AI and may have been edited. Recorded values and calculated summaries are presented separately. AI can make mistakes: check the overview against original records before sharing.</p><p>For personal information. This report does not provide a diagnosis or treatment recommendation.</p></aside>` : `<p class="report-origin-note">Compiled from selected records. No new AI overview was generated for this report; source records may contain earlier AI-assisted content. For personal information, not a diagnosis or treatment recommendation.</p>`;
}

export function renderConciseReportBody(report: ReportDataSnapshot | JSONDetached<ReportDataSnapshot>, options: ConciseReportOptions, headerFacts: readonly ReportHeaderFact[], aiHTML = '') {
  const sections = new Set(options.sections);
  const selected = (id: string) => sections.has(id);
  const appendices = new Set(options.appendixSections || []);
  const parts: { id: string; title: string; content: string }[] = [];
  const add = (id: string, title: string, content: string) => {
    parts.push({ id, title, content: `<section id="report-${id}" class="report-summary-section"><h2>${esc(title)}</h2>${content}</section>` });
  };
  const appendixHint = (id: string | undefined) => appendices.has(id!) ? '<p class="report-note">Individual records and extended context are in the <a href="#report-appendix">appendix</a>.</p>' : '';
  const labs = report.labs;
  if (labs) {
    const rows: unknown[][] = [];
    const statuses: string[] = [];
    const sourceLabels: Record<string, string> = { schema: 'App guidance', context: 'App context', custom: 'Custom', phase: 'Cycle phase', lab: 'Lab' };
    for (const category of labs.categories) for (const marker of category.markers) {
      const latest = marker.latestResult || marker.results?.at(-1);
      if (!latest) continue;
      if (!selected('categories') && selected('flagged') && !['low', 'high'].includes(latest.status)) continue;
      const previous = marker.results.filter(result => result.date && latest.date && result.date < latest.date).at(-1);
      const ranges = latest.ranges.displayed;
      const reference = latest.ranges.available.find(range => range.kind !== 'optimal');
      const referenceStatus = reference?.min != null || reference?.max != null ? getStatus(latest.value, reference.min, reference.max) : 'unrated';
      const status = options.rangeMode === 'both' ? `Reference: ${referenceStatus}\nSelected status: ${latest.status} (${latest.ranges.judging.label})` : `${latest.status} (${latest.ranges.judging.label})`;
      statuses.push(latest.status);
      rows.push([`${marker.name}\n${category.label}${marker.calculated ? ' · calculated' : ''}`, `${latest.displayValue} ${marker.unit}\n${latest.date || 'Undated'}${latest.note ? '\n' + excerpt(latest.note, 150) : ''}`,
        previous ? `${previous.displayValue} ${marker.unit}\n${previous.date}` : 'No earlier dated result',
        ranges.map(range => `${range.label}: ${bounds(range)} (${sourceLabels[range.source] || 'Source not specified'})`).join('\n'), status]);
    }
    add('labs', 'Lab results — latest and previous', `${labs.dates.length ? '' : '<p>No lab dates in selected range.</p>'}<p class="report-copy">${labs.summary.markerCount} marker${labs.summary.markerCount === 1 ? '' : 's'} with data; ${labs.summary.latestOutOfRangeCount} outside the selected range. “Outside range” does not indicate urgency. Previous values are recorded comparisons; collection conditions and ranges may differ.</p>${table(['Marker / group', 'Latest', 'Previous', 'Latest ranges / source', 'Range status'], rows, 'report-lab-summary', statuses)}<p class="report-note">${options.rangeMode === 'reference' ? 'Reference ranges judge status.' : 'Optimal guidance judges status when available; otherwise reference ranges. Phase-specific ranges take precedence.'} No lab results are averaged.</p>${['categories', 'flagged', 'trends', 'summary'].some(id => appendices.has(id)) ? appendixHint([...appendices].find(id => ['categories', 'flagged', 'trends', 'summary'].includes(id))) : ''}`);
  }
  if (selected('supplements')) {
    const current = report.supplements.filter(s => getSupplementStatus(s) !== 'ended');
    const rows = current.map(s => [s.name || 'Unnamed', s.type || 'Type not provided', getSupplementStatus(s),
      getSupplementDosageParts(s).filter(part => !/^(Other label ingredients|Source-reported laboratory results):/.test(part)).join('; ') || 'Dose not provided',
      getSupplementPeriods(s).map(period => `${period.start || 'start not recorded'} → ${period.end || 'ongoing'}`).join('; ')]);
    add('therapy', 'Reported medicines and supplements', `${rows.length ? table(['Name', 'Type', 'Status', 'Reported dose / frequency', 'Periods'], rows) : '<p>No current therapy records provided.</p>'}<p class="report-note">User-reported records, not a reconciled medication list. ${report.supplements.length - current.length} ended records are available in the optional appendix. Allergy status is not established by this list.</p>${appendixHint('supplements')}`);
  }
  if (selected('context') && report.context?.sections.length) {
    add('context', 'Selected personal context', table(['Topic', 'User-reported context'], report.context.sections.map(section => [section.title, excerpt(section.text)])) + '<p class="report-note">Long entries are labeled as excerpts; add the context appendix for complete text.</p>' + appendixHint('context'));
  }
  for (const section of report.additionalSections || []) {
    if (!selected(section.id)) continue;
    const summary = section.summary || section;
    const columns = section.id === 'nutrition' ? summary.columns.slice(0, 3) : summary.columns;
    const rows = section.id === 'nutrition' ? summary.rows.map(row => [row[0], row[1] === 'Insufficient recorded values' && row[3] !== '—' ? `Recorded total: ${row[3]}; no daily average` : row[1], row[2]]) : summary.rows;
    add(section.id, section.title, `<p class="report-note">${esc(summary.note)}${section.id === 'wearables' ? ' ' + esc(section.note) : ''}</p>${summary.rows.length ? table(columns, rows, 'report-history-summary') : '<p>No records available in the selected period.</p>'}${appendixHint(section.id)}`);
  }
  if (selected('genetics') && report.genetics) {
    const genetics = report.genetics;
    const findings = genetics.findings || [];
    const chosen = selectReportGenomeFindings(genetics, options);
    let content = `<p class="report-copy">Source: ${esc(genetics.source || 'Not specified')}. Imported: ${esc(genetics.importDate || 'not recorded')}. ${findings.length} imported calls; ${chosen.length} selected for discussion.${genetics.coverage ? ` Catalog coverage at import: ${esc(genetics.coverage.found)} / ${esc(genetics.coverage.total)}.` : ''}</p>`;
    if (genetics.apoe && (options.genomeMode === 'all' || (!options.genomeMode && !findings.length) || chosen.some(finding => ['rs429358', 'rs7412'].includes(finding.rsid)))) content += `<p>Reported APOE: ${esc(genetics.apoe)}</p>`;
    if (!chosen.length) content += '<p>No findings match this selection in the current catalog. This does not rule out genetic risk.</p>';
    if (chosen.length) content += `<table class="genetics-table"><thead><tr><th>Variant / genotype</th><th>Direction</th><th>Evidence / relevance</th><th>Catalog interpretation / sources</th></tr></thead><tbody>${chosen.map(f => {
      const tone = ['risk', 'protective', 'trait'].includes(f.tone) ? f.tone : 'neutral';
      return `<tr><td>${cell(`${f.gene} ${f.variant}\n${f.rsid}: ${f.genotype}`)}</td><td><span class="genome-direction genome-${tone}">${esc(f.direction)}</span></td><td>${cell(`${f.evidence.evidenceLabel}\n${f.evidence.relevanceLabel}`)}</td><td>${cell(f.note)}<br>${(f.references || []).map(reportReference).join('; ')}</td></tr>`;
    }).join('')}</tbody></table>`;
    content += `<p class="report-note">Associations are not diagnoses or a clinical action ranking. Evidence strength and personal relevance are separate. ${findings.length - chosen.length} calls are not expanded in this summary.${genetics.mtdna && (!options.genomeMode || options.genomeMode === 'all') ? ` Maternal lineage: ${esc(genetics.mtdna.haplogroup || 'not specified')}; lineage is not a measured health effect.` : ''}</p>${appendixHint('genetics')}`;
    add('genetics', 'Genome — selected findings', content);
  }
  if (selected('notes')) {
    const notes = [...report.notes].sort((a, b) => String(a.date || '').localeCompare(String(b.date || '')));
    add('notes', 'Recent notes', table(['Date', 'Note'], notes.slice(-5).map(note => [note.date || 'Undated', excerpt(note.text)])) + `<p class="report-note">${Math.min(5, notes.length)} of ${notes.length} notes shown; long notes are excerpts.</p>${appendixHint('notes')}`);
  }
  const meta = headerFacts.filter(fact => ['DOB / Age', 'Sex', 'Range display', 'Units', 'History window'].includes(fact.label));
  const coverage = (report.additionalSections || []).map(section => `${section.title}: ${section.rows.length} source records`).join(' · ');
  return `<div class="report-preview-toolbar"><button type="button" class="report-print-btn" data-report-print-action="print">Print / Save PDF</button></div><header class="report-header" id="report-top"><div class="report-brand">getbased · ${esc(options.presetLabel)}</div><h1>${esc(report.profile.name)} health report</h1>${renderReportOriginNotice(options.aiSummary)}<p class="report-deck">Personal records summary · Generated ${esc(report.generatedAt.slice(0, 10))}</p><dl class="report-meta">${meta.map(fact => `<div><dt>${esc(fact.label)}</dt><dd>${esc(fact.value)}</dd></div>`).join('')}</dl></header>
    <section class="report-purpose"><h2>Reason for sharing / questions</h2><p>${cell(options.purpose || 'Not provided. Use this report to discuss the selected recorded findings and their context.')}</p></section>
    <p class="report-note">${labs ? `Latest lab date: ${esc(labs.dates.at(-1) || 'not recorded')}. ` : 'Lab results not selected. '}${coverage ? esc(coverage) + '. ' : ''}Source-specific coverage is shown below; unlogged days are unknown.</p>
    <nav class="report-contents" aria-label="Report contents">${parts.map(part => `<a href="#report-${part.id}">${esc(part.title.split(' — ')[0]!)}</a>`).join(' · ')}${appendices.size ? ' · <a href="#report-appendix">Appendix</a>' : ''}</nav>
    ${aiHTML}${parts.map(part => part.content).join('')}`;
}
