type MtDnaFixture = NonNullable<NonNullable<Parameters<typeof import('../../js/dna.js').detectMtDNAMismatch>[0]>['mtdna']>;
type MtDnaMismatchFixture = { mtdna: Omit<MtDnaFixture, 'coupling'> & { coupling: Partial<NonNullable<MtDnaFixture['coupling']>> } };
import type { DnaProfileData, PendingDnaImport } from '../../js/dna-runtime.js';
import type { PendingMtDnaImport } from '../../js/dna-mtdna.js';
import { createBlankPage } from '../helpers/browser-blank-page.js';
import { expect, test } from './coverage-fixture.js';

const openBlankPage = createBlankPage({
  body: '<!doctype html><html><head><title>DNA coverage</title></head><body></body></html>',
});

test('DNA parser browser coverage exercises real File, Worker, and context paths', async ({ page }) => {
  await openBlankPage(page, '/dna-parser-browser-coverage');

  const results = await page.evaluate(async () => {
    const failures: unknown[] = [];
    const check = (name: string, condition: unknown, detail = '') => {
      if (!condition) failures.push(detail ? `${name}: ${detail}` : name);
    };
    const textFile = (content: BlobPart, name: string, type = 'text/plain') => new File([content], name, { type });

    const { state } = await import('/js/state.js');
    const dna = (await import(`/js/dna.js?dnaParserCoverage=${Date.now()}-${Math.random()}`) as unknown) as Pick<typeof import('../../js/dna.js'), "detectDNAFile" | "isDNAFile" | "isDNAFileByContent" | "getSnpCategoryLabel" | "parseDNAFile" | "findGenotypeInfo" | "findSnpHint" | "saveGeneticsData" | "buildFullGeneticsContext" | "buildGeneticsContext" | "deleteGeneticsData" | "ensureSNPTable" | "handleDNAFile" | "upsertGeneticsSnp" | "renderGeneticsSection" | "loadHaplogroupTable" | "parseMtDNAMutations" | "resolveHaplogroup" | "detectMtDNAMismatch" | "handleMtDNAFile" | "setManualHaplogroup" | "ensureHaplogroupTable" | "HAPLOGROUP_LIST">;

    state.currentProfile = `dna-parser-coverage-${Date.now()}`;
    (state as { importedData: unknown }).importedData = { entries: [], notes: [], supplements: [], healthGoals: [], diagnoses: null, genetics: null, customMarkers: {}, markerNotes: {}, markerValueNotes: {}, changeHistory: [] };

    const annotatedReportCsv =
      'rsID,Gene,Category,Genotype,Zygosity,Risk_Allele,Result,Read_Depth,Annotation,Source\n' +
      'rs429358,APOE,Lipids,-,-,-,e3/e3,-,APOE part 1,variant-VCF\n' +
      'rs7412,APOE,Lipids,-,-,-,e3/e3,-,APOE part 2,variant-VCF\n' +
      'rs1801133,MTHFR,Methylation,wildtype,Homozygous reference,T,Risk allele absent,-,C677T wildtype,variant-VCF\n' +
      'rs1805087,MTR,Methylation,het,Heterozygous,G,One copy,-,A2756G modifier,variant-VCF\n' +
      'rs1800562,HFE,Iron Metabolism,-,-,A,non-carrier,-,C282Y negative,variant-VCF\n';
    const ancestryContent = `#AncestryDNA raw data download
#This file was generated by AncestryDNA
rsid\tchromosome\tposition\tallele1\tallele2
rs1801133\t1\t11856378\tG\tA
rs1801131\t1\t11854476\tT\tT
rs1800562\t6\t26093141\tG\tG
rs429358\t19\t45411941\tT\tC
rs7412\t19\t45412079\tC\tC
rs174546\t11\t61569830\tC\tT
rs999999\t1\t100000\tA\tG
`;
    const me23Content = `# This data file generated by 23andMe at: 2024-01-01
# rsid\tchromosome\tposition\tgenotype
rs1801133\t1\t11856378\tGA
rs1800562\t6\t26093141\tGG
rs174546\t11\t61569830\tCT
i123456\t1\t100\tAA
`;
    const csvContent = `RSID,CHROMOSOME,POSITION,RESULT
"rs1801133","1","11856378","GA"
"rs1800562","6","26093141","GG"
`;
    const myHeritageWgsContent =
      '##fileformat=MyHeritage\n' +
      '##method=Low-pass Whole Genome Sequencing\n' +
      'RSID,CHROMOSOME,POSITION,RESULT\n' +
      '"rs5882","16","57016092","AG"\n' +
      '"rs762551","15","75041917","AC"\n' +
      '"rs11591147","1","55505647","AC"\n' +
      '"rs1801394","5","7870973","TT"\n' +
      '"rs1805087","1","237048500","CC"\n' +
      '"rs11206244","1","54375701","CG"\n';
    const illuminaContent =
      '\uFEFF[Header]\n' +
      'GSGT Version,2.0.5\n' +
      '[Data]\n' +
      'Sample Name,SNP Name,Chr,Position,Allele1 - Plus,Allele2 - Plus\n' +
      'sample1,seq-rs1801133,1,11856378,G,A\n' +
      'sample1,BOT-rs1800562,6,26093141,G,G\n' +
      'sample1,ilmnseq_rs174546_ilmnTOP_5AT,11,61569830,C,T\n';

    check('detects Ancestry', dna.detectDNAFile('#AncestryDNA raw data download\n') === 'ancestry');
    check('detects 23andMe autosomal', dna.detectDNAFile('# This data file generated by 23andMe\nrs123\t1\t100\tAG\n') === '23andme');
    check('detects 23andMe mito', dna.detectDNAFile('# This data file generated by 23andMe\nrs1\tMT\t263\tG\nrs2\tMT\t750\tG\n') === '23andme-mito');
    check('detects 23andMe Y', dna.detectDNAFile('# This data file generated by 23andMe\nrs1\tY\t100\tA\nrs2\tY\t101\tC\n') === '23andme-y');
    check('detects Living DNA', dna.detectDNAFile('# Living DNA customer genotype data download file version: 1.0.1\n') === 'livingdna');
    check('detects Living DNA motherline markers',
      dna.detectDNAFile('# Living DNA customer genotype data download file version: 1.0.1\n263G\n750G\n1438G\n') === 'mtdna');
    check('detects quoted CSV', dna.detectDNAFile('"RSID","CHROMOSOME","POSITION","RESULT"\n') === 'csv');
    check('detects headerless 23andMe', dna.detectDNAFile('rs123\t1\t100\tAG\n') === '23andme');
    check('detects annotated report', dna.detectDNAFile(annotatedReportCsv) === 'annotated-snp-report');
    check('detects mtDNA short list', dna.detectDNAFile('263G\n750G\n1438G\n4769G\n8860G\n15326G\n') === 'mtdna');
    check('rejects JSON detection', dna.detectDNAFile('{"entries":[]}') === null);
    check('filename positive', dna.isDNAFile({ name: 'MyHeritage_raw_dna_data.csv' }) === true);
    check('filename negative', dna.isDNAFile({ name: 'lab-results.pdf' }) === false);
    check('content positive', await dna.isDNAFileByContent(textFile(ancestryContent, 'ancestry.txt')) === true);
    check('content negative', await dna.isDNAFileByContent(textFile('not dna', 'notes.txt')) === false);
    check('content read failure returns false', await dna.isDNAFileByContent({ slice() { throw new Error('slice failed'); } }) === false);
    check('category label fallback', dna.getSnpCategoryLabel('missing') === 'missing' && dna.getSnpCategoryLabel(null) === 'Other');

    const ancestry = await dna.parseDNAFile(textFile(ancestryContent, 'AncestryDNA.txt'));
    const me23 = await dna.parseDNAFile(textFile(me23Content, '23andme.txt'));
    const csv = await dna.parseDNAFile(textFile(csvContent, 'Family_Finder_Results.csv', 'text/csv'));
    const annotated = await dna.parseDNAFile(textFile(annotatedReportCsv, 'report.csv', 'text/csv'));
    const wgs = await dna.parseDNAFile(textFile(myHeritageWgsContent, 'MyHeritage_raw_dna_data_adj.csv', 'text/csv'));
    const illumina = await dna.parseDNAFile(textFile(illuminaContent, 'dnaera.csv', 'text/csv'));

    let invalidMessage = '';
    try {
      await dna.parseDNAFile(textFile('%PDF-1.4', 'not-dna.txt'));
    } catch (error) {
      invalidMessage = (error as { message: string }).message;
    }

    check('ancestry source and matches', ancestry.source === 'AncestryDNA' && ancestry.matches.rs1801133?.genotype === 'GA');
    check('ancestry skips unknown rsid', ancestry.matches.rs999999 == null);
    check('23andMe source and internal id skip', me23.source === '23andMe' && me23.matches.rs1801133?.genotype === 'GA' && me23.matches.i123456 == null);
    check('CSV parser handles quoted fields', csv.source === 'MyHeritage/FTDNA' && csv.matches.rs1800562?.genotype === 'GG');
    check('annotated report infers APOE and carrier states',
      annotated.source === 'Annotated SNP report' &&
      annotated.matches.rs429358?.genotype === 'TT' &&
      annotated.matches.rs7412?.genotype === 'CC' &&
      annotated.matches.rs1801133?.genotype === 'GG' &&
      annotated.matches.rs1805087?.genotype === 'AG' &&
      annotated.matches.rs1800562?.genotype === 'GG');
    check('WGS strand-aware parser keeps valid and drops invalid calls',
      wgs.matches.rs5882?.effect === 'none' &&
      wgs.matches.rs5882?.valence === 'informational' &&
      wgs.matches.rs11591147?.effect === 'significant' &&
      wgs.matches.rs1805087?.effect === 'none' &&
      wgs.matches.rs1805087?.valence === 'informational' &&
      wgs.matches.rs11206244 == null);
    check('Illumina parser unwraps probe rsids', illumina.source.includes('Illumina') && illumina.matches.rs1801133?.genotype === 'GA');
    check('invalid parser throws useful message', /Unrecognized DNA file format/.test(invalidMessage));

    const nonPalEntry = { genotypes: { AA: { effect: 'none' }, AG: { effect: 'moderate' }, GG: { effect: 'significant' } }, snpHints: { AG: { slotKey: 'coagulation.homocysteine' } } };
    const palEntry = { genotypes: { CC: { effect: 'none' }, CG: { effect: 'moderate' }, GG: { effect: 'significant' } } };
    check('strand-aware direct reverse and RC lookup',
      dna.findGenotypeInfo(nonPalEntry, 'GA')?.effect === 'moderate' &&
      dna.findGenotypeInfo(nonPalEntry, 'CT')?.effect === 'moderate' &&
      dna.findSnpHint(nonPalEntry, 'GA')?.slotKey === 'coagulation.homocysteine');
    check('palindromic guard suppresses unsafe RC lookup',
      dna.findGenotypeInfo(palEntry, 'CC')?.effect === 'none' &&
      dna.findGenotypeInfo(palEntry, 'AA') == null);

    const profileData: DnaProfileData = {};
    dna.saveGeneticsData(profileData, ancestry);
    const fullContext = dna.buildFullGeneticsContext(profileData.genetics);
    const filteredContext = dna.buildGeneticsContext(profileData.genetics, ['coagulation.homocysteine']);
    const filteredContextWithInventory = dna.buildGeneticsContext(profileData.genetics, ['coagulation.homocysteine'], { includeSnpInventory: true });
    const emptyContext = dna.buildGeneticsContext(null, []);
    check('saveGeneticsData resolves APOE and effects',
      profileData.genetics?.apoe === '\u03B53/\u03B54' &&
      profileData.genetics.effects!.moderate! >= 1 &&
      profileData.genetics.snps!.rs1801133?.category === 'methylation' &&
      profileData.genetics.catalogVersion?.size! > 0);
    check('genetics context includes filtered genetics',
      fullContext.startsWith('GENETICS (') &&
      fullContext.includes('APOE: \u03B53/\u03B54') &&
      fullContext.includes('Imported SNP inventory for lookup') &&
      fullContext.includes('HFE C282Y rs1800562: GG (reference finding') &&
      filteredContext.includes('MTHFR') &&
      !filteredContext.includes('FADS1') &&
      !filteredContext.includes('Imported SNP inventory for lookup') &&
      filteredContextWithInventory.includes('FADS1') &&
      !filteredContextWithInventory.includes('Intermediate desaturase activity') &&
      emptyContext === '');
    dna.deleteGeneticsData(profileData);
    check('deleteGeneticsData removes data', profileData.genetics === undefined);

    state.importedData.genetics = { source: 'stub', snps: { rs1801133: { genotype: 'GA' } } };
    check('ensureSNPTable loads when genetics exists', await dna.ensureSNPTable() != null);

    return { failures };
  });

  expect(results.failures).toEqual([]);
});

test('DNA autosomal import UI coverage exercises preview, confirm, render, and delete paths', async ({ page }) => {
  await openBlankPage(page, '/dna-autosomal-ui-browser-coverage');

  const results = await page.evaluate(async () => {
    const failures: unknown[] = [];
    const check = (name: string, condition: unknown, detail = '') => {
      if (!condition) failures.push(detail ? `${name}: ${detail}` : name);
    };
    const textFile = (content: BlobPart, name: string, type = 'text/plain') => new File([content], name, { type });
    const wait = () => new Promise((resolve) => setTimeout(resolve, 0));
    const waitFor = async (predicate: () => unknown | Promise<unknown>) => {
      for (let i = 0; i < 100; i++) {
        if (predicate()) return true;
        await wait();
      }
      return false;
    };

    const { state } = await import('/js/state.js');
    const dna = (await import(`/js/dna.js?dnaAutosomalCoverage=${Date.now()}-${Math.random()}`) as unknown) as Pick<typeof import('../../js/dna.js'), "detectDNAFile" | "isDNAFile" | "isDNAFileByContent" | "getSnpCategoryLabel" | "parseDNAFile" | "findGenotypeInfo" | "findSnpHint" | "saveGeneticsData" | "buildFullGeneticsContext" | "buildGeneticsContext" | "deleteGeneticsData" | "ensureSNPTable" | "handleDNAFile" | "upsertGeneticsSnp" | "renderGeneticsSection" | "loadHaplogroupTable" | "parseMtDNAMutations" | "resolveHaplogroup" | "detectMtDNAMismatch" | "handleMtDNAFile" | "setManualHaplogroup" | "ensureHaplogroupTable" | "HAPLOGROUP_LIST">;
    const dnaRuntime = await import('/js/dna-runtime.js');
    const chatRuntime = await import('/js/chat-runtime.js');
    let importRunning = false;
    const previousDnaRuntimeDeps = dnaRuntime.configureDnaRuntimeDeps();

    const profileId = `dna-autosomal-coverage-${Date.now()}`;
    state.currentProfile = profileId;
    (state as { importedData: unknown }).importedData = { entries: [], notes: [], supplements: [], healthGoals: [], diagnoses: null, genetics: null, customMarkers: {}, markerNotes: {}, markerValueNotes: {}, changeHistory: [] };
    state.profiles = [{ id: profileId, name: 'DNA coverage', createdAt: Date.now(), lastUpdated: Date.now(), tags: [], notes: '', status: 'active', pinned: false }];

    document.body.innerHTML = '<div id="notification-container"></div><div class="chat-onboard-dna"></div><main id="fixture"></main>';
    const calls: unknown[] = [];
    dnaRuntime.configureDnaRuntimeDeps({
      buildSidebar: () => calls.push('sidebar'),
      isImportRunning: () => importRunning,
      navigate: (route: unknown) => calls.push(`navigate:${route}`),
    });
    const previousChatRuntime = chatRuntime.configureChatRuntimeCallbacks({
      updateChatNudge: () => calls.push('nudge'),
    });

    const validContent = `#AncestryDNA raw data download
rsid\tchromosome\tposition\tallele1\tallele2
rs1801133\t1\t11856378\tG\tA
rs1801131\t1\t11854476\tT\tG
rs1800562\t6\t26093141\tG\tG
rs429358\t19\t45411941\tT\tC
rs7412\t19\t45412079\tC\tC
rs174546\t11\t61569830\tC\tT
rs5882\t16\t57016092\tA\tG
`;
    const noMatchContent = `# This data file generated by 23andMe at: 2024-01-01
rs999999\t1\t100\tAG
`;

    importRunning = true;
    const busyImport = await dna.handleDNAFile(textFile(validContent, 'busy.txt'));
    check('busy import reports failure and blocks preview',
      busyImport === false && !document.getElementById('dna-modal-overlay')?.classList.contains('show'));
    importRunning = false;

    const noMatchImport = await dna.handleDNAFile(textFile(noMatchContent, 'nomatch.txt'));
    check('no-match file reports failure and does not open preview',
      noMatchImport === false && !document.getElementById('dna-modal-overlay')?.classList.contains('show'));

    const validImport = await dna.handleDNAFile(textFile(validContent, 'ancestry-ui.txt'));
    await wait();
    let overlay = document.getElementById('dna-modal-overlay');
    check('valid file reports success and opens DNA preview',
      validImport === true && overlay?.classList.contains('show') === true);
    check('preview stores pending import', (window as { _pendingDNAImport?: PendingDnaImport | null })._pendingDNAImport?.coverage?.found! > 0);
    check('DNA preview uses delegated actions', !overlay?.querySelector('[onclick], [onkeydown]'));
    overlay?.querySelector<HTMLElement>('.dna-preview-collapsible')?.click();
    check('collapsible preview group toggles', overlay?.querySelector('.dna-preview-group.expanded') != null);
    overlay?.querySelector<HTMLElement>('[data-dna-action="close-preview"]')?.click();
    await wait();
    check('close preview clears pending import', (window as { _pendingDNAImport?: PendingDnaImport | null })._pendingDNAImport == null && !overlay?.classList.contains('show'));

    const manualOverride = dna.upsertGeneticsSnp(state.importedData, 'rs1801133', 'CC', {
      type: 'manual',
      label: 'Clinical manual override',
    });
    await dna.handleDNAFile(textFile(validContent, 'ancestry-confirm.txt'));
    const importConfirmReady = await waitFor(() => document.querySelector('[data-dna-action="confirm-import"]') != null);
    overlay = document.getElementById('dna-modal-overlay');
    const mthfrPreviewRow = Array.from(overlay?.querySelectorAll('.dna-preview-row') || [])
      .find(row => row.textContent?.includes('C677T'))?.textContent || '';
    check('raw re-import preview shows the authoritative preserved override',
      mthfrPreviewRow.includes('CC') &&
      !mthfrPreviewRow.includes('GA') &&
      overlay?.querySelector('.dna-preview-stats')?.textContent.includes('1 curated override'),
      `${mthfrPreviewRow} | ${overlay?.querySelector('.dna-preview-stats')?.textContent || ''}`);
    overlay?.querySelector<HTMLElement>('[data-dna-action="confirm-import"]')?.click();
    const importFinished = importConfirmReady && await waitFor(() => !overlay?.classList.contains('show') && calls.includes('navigate:dashboard'));
    check('confirmDNAImport preserves an overlapping manual genotype',
      manualOverride.ok === true &&
      state.importedData.genetics?.snps?.rs1801133?.genotype === 'CC' &&
      state.importedData.genetics?.snps?.rs1801133?.source?.type === 'manual');
    check('confirmDNAImport closes preview and refreshes', importFinished && calls.includes('sidebar'));
    const importConfirmation = document.querySelector('.chat-onboard-dna')?.textContent || '';
    check('chat onboarding confirmation uses authoritative saved findings',
      importConfirmation.includes('7 SNP calls available') &&
      importConfirmation.includes('1 risk association') &&
      importConfirmation.includes('2 informational traits') &&
      importConfirmation.includes('2 reference / neutral findings') &&
      !importConfirmation.includes('2 risk associations'),
      importConfirmation);

    const html = dna.renderGeneticsSection();
    document.getElementById('fixture')!.innerHTML = html;
    check('renderGeneticsSection returns populated genetics UI',
      document.querySelector('.genetics-section') != null &&
      document.querySelector('.genetics-overview-card')?.textContent.includes('Catalog coverage'));
    check('renderGeneticsSection uses delegated actions', !document.querySelector('.genetics-section')?.querySelector('[onclick], [onkeydown]'));
    document.querySelector<HTMLElement>('.section-header')?.click();
    check('toggleGeneticsCollapse hides body', document.querySelector('.genetics-body')?.classList.contains('hidden'));
    document.querySelector('.section-header')?.dispatchEvent(new KeyboardEvent('keydown', { key: ' ', bubbles: true }));
    check('toggleGeneticsCollapse shows body', !document.querySelector('.genetics-body')?.classList.contains('hidden'));

    document.querySelector('.genetics-section')?.insertAdjacentHTML('beforeend', '<button id="expand" data-dna-action="toggle-genetics-expand">More</button>');
    document.getElementById('expand')?.click();
    check('toggleGeneticsExpand expands fixture', document.querySelector('.genetics-findings')?.classList.contains('expanded') && document.getElementById('expand')!.textContent === 'Show less');

    const originalCreateElement = document.createElement.bind(document);
    let clickedSyntheticInput = false;
    document.createElement = (tagName: string) => {
      const el = originalCreateElement(tagName);
      if (String(tagName).toLowerCase() === 'input') {
        el.click = () => { clickedSyntheticInput = true; };
      }
      return el;
    };
    document.querySelector<HTMLElement>('[data-dna-action="reimport-dna"]')?.click();
    document.createElement = originalCreateElement;
    check('reimportDNA opens file picker', clickedSyntheticInput);

    document.querySelector<HTMLElement>('[data-dna-action="delete-dna"]')?.click();
    const confirmReady = await waitFor(() => document.getElementById('confirm-ok') != null);
    document.getElementById('confirm-ok')?.click();
    const deleteFinished = confirmReady && await waitFor(() => state.importedData.genetics == null && calls.filter(item => item === 'navigate:dashboard').length >= 2);
    check('confirmDeleteDNA deletes genetics and refreshes', deleteFinished);

    const toastText = document.getElementById('notification-container')?.textContent || '';
    check('notifications rendered during flow', /DNA import|Imported|health-relevant/.test(toastText));

    dnaRuntime.configureDnaRuntimeDeps(previousDnaRuntimeDeps);
    chatRuntime.configureChatRuntimeCallbacks(previousChatRuntime);
    return { failures };
  });

  expect(results.failures).toEqual([]);
});

test('DNA mtDNA browser coverage exercises haplogroup parsing, preview, import, mismatch, and manual paths', async ({ page }) => {
  await openBlankPage(page, '/dna-mtdna-browser-coverage');

  const results = await page.evaluate(async () => {
    const failures: unknown[] = [];
    const check = (name: string, condition: unknown, detail = '') => {
      if (!condition) failures.push(detail ? `${name}: ${detail}` : name);
    };
    const textFile = (content: BlobPart, name: string, type = 'text/plain') => new File([content], name, { type });
    const wait = () => new Promise((resolve) => setTimeout(resolve, 0));
    const waitFor = async (predicate: () => unknown | Promise<unknown>) => {
      for (let i = 0; i < 100; i++) {
        if (predicate()) return true;
        await wait();
      }
      return false;
    };

    const { state } = await import('/js/state.js');
    const [dna, dnaRuntime] = await Promise.all([
      (import(`/js/dna.js?dnaMtdnaCoverage=${Date.now()}-${Math.random()}`) as Promise<unknown>) as Promise<Pick<typeof import('../../js/dna.js'), "detectDNAFile" | "isDNAFile" | "isDNAFileByContent" | "getSnpCategoryLabel" | "parseDNAFile" | "findGenotypeInfo" | "findSnpHint" | "saveGeneticsData" | "buildFullGeneticsContext" | "buildGeneticsContext" | "deleteGeneticsData" | "ensureSNPTable" | "handleDNAFile" | "upsertGeneticsSnp" | "renderGeneticsSection" | "loadHaplogroupTable" | "parseMtDNAMutations" | "resolveHaplogroup" | "detectMtDNAMismatch" | "handleMtDNAFile" | "setManualHaplogroup" | "ensureHaplogroupTable" | "HAPLOGROUP_LIST">>,
      import('/js/dna-runtime.js'),
    ]);
    const previousDnaRuntimeDeps = dnaRuntime.configureDnaRuntimeDeps();

    const profileId = `dna-mtdna-coverage-${Date.now()}`;
    state.currentProfile = profileId;
    (state as { importedData: unknown }).importedData = { entries: [], notes: [], supplements: [], healthGoals: [], diagnoses: null, genetics: null, customMarkers: {}, markerNotes: {}, markerValueNotes: {}, changeHistory: [] };
    state.profiles = [{ id: profileId, name: 'mtDNA coverage', createdAt: Date.now(), lastUpdated: Date.now(), tags: [], notes: '', status: 'active', pinned: false }];

    document.body.innerHTML = '<div id="notification-container"></div><main id="fixture"></main>';
    const calls: unknown[] = [];
    dnaRuntime.configureDnaRuntimeDeps({
      buildSidebar: () => calls.push('sidebar'),
      navigate: (route: unknown) => calls.push(`navigate:${route}`),
    });

    const hapTable = await dna.loadHaplogroupTable();
    const jText = '295T\n489C\n4216C\n10398G\n11251G\n12612G\n13708A\n16069T\n16126C\n';
    const mt23Text = '# This data file generated by 23andMe\nrs1\tMT\t295\tT\nrs2\tMT\t4216\tC\nrs3\tMT\t10398\tG\nrs4\tMT\t13708\tA\nrs5\tMT\t16069\tT\nrs6\tMT\t16126\tC\n';
    const jMutations = dna.parseMtDNAMutations(jText);
    const mt23Mutations = dna.parseMtDNAMutations(mt23Text);
    const hMutations = dna.parseMtDNAMutations('263G\n750G\n1438G\n4769G\n8860G\n15326G\n');
    const directHMutations = dna.parseMtDNAMutations('2706A\n7028C\n');
    const resolvedJ = dna.resolveHaplogroup(jMutations, hapTable);
    const resolvedH = dna.resolveHaplogroup(hMutations, hapTable);
    const resolvedDirectH = dna.resolveHaplogroup(directHMutations, hapTable);
    check('parseMtDNAMutations handles simple and 23andMe rows', jMutations.length === 9 && mt23Mutations.length === 6 && mt23Mutations[0]!.raw === '295T');
    check('resolveHaplogroup resolves direct, diagnostic H, and H fallback',
      resolvedJ?.haplogroup === 'J' && resolvedDirectH?.haplogroup === 'H' && resolvedH?.haplogroup === 'H');

    dnaRuntime.configureDnaRuntimeDeps({ getLatitudeFromLocation: () => '<25\u00B0 latitude (tropical)' });
    const mismatch = (dna.detectMtDNAMismatch as (genetics: MtDnaMismatchFixture) => ReturnType<typeof dna.detectMtDNAMismatch>)({
      mtdna: {
        haplogroup: 'J',
        coupling: { shortLabel: 'uncoupled', climate: 'Cold (Northern European)', matchedLatBands: [3, 4], implications: 'test implications' },
      },
    });
    dnaRuntime.configureDnaRuntimeDeps({ getLatitudeFromLocation: () => '50-60\u00B0 (northern)' });
    const matched = (dna.detectMtDNAMismatch as (genetics: MtDnaMismatchFixture) => ReturnType<typeof dna.detectMtDNAMismatch>)({
      mtdna: {
        haplogroup: 'J',
        coupling: { shortLabel: 'uncoupled', climate: 'Cold (Northern European)', matchedLatBands: [3, 4] },
      },
    });
    dnaRuntime.configureDnaRuntimeDeps({ getLatitudeFromLocation: () => 'unknown' });
    const invalidBand = (dna.detectMtDNAMismatch as (genetics: MtDnaMismatchFixture) => ReturnType<typeof dna.detectMtDNAMismatch>)({ mtdna: { haplogroup: 'J', coupling: { matchedLatBands: [3, 4] } } });
    check('detectMtDNAMismatch covers mismatch, match, invalid band', mismatch?.mismatch === true && matched?.mismatch === false && invalidBand === null);

    const emptyMtDnaImport = await dna.handleMtDNAFile(textFile('not mtdna', 'empty-mtdna.txt'));
    check('empty mtDNA file reports failure and does not open preview',
      emptyMtDnaImport === false && !document.getElementById('dna-modal-overlay')?.classList.contains('show'));

    dnaRuntime.configureDnaRuntimeDeps({ getLatitudeFromLocation: () => '<25\u00B0 latitude (tropical)' });
    const validMtDnaImport = await dna.handleMtDNAFile(textFile(jText, 'genome-mtdna.txt'));
    await wait();
    let overlay = document.getElementById('dna-modal-overlay');
    check('handleMtDNAFile reports success and opens preview',
      validMtDnaImport === true && overlay?.classList.contains('show') === true && (window as { _pendingMtDNA?: PendingMtDnaImport | null })._pendingMtDNA?.resolved?.haplogroup === 'J');
    check('mtDNA preview includes mismatch', overlay?.textContent.includes('Environment mismatch'));
    check('mtDNA preview describes diagnostic marker overlap without a confidence percentage',
      overlay?.textContent.includes('diagnostic markers matched') && !overlay?.querySelector('.mtdna-hg-confidence')?.textContent.includes('%'));
    check('mtDNA preview uses delegated actions', !overlay?.querySelector('[onclick], [onkeydown]'));
    overlay?.querySelector<HTMLElement>('[data-dna-action="close-mtdna-preview"]')?.click();
    await wait();
    check('closeMtDNAPreview clears pending', (window as { _pendingMtDNA?: PendingMtDnaImport | null })._pendingMtDNA == null && !overlay?.classList.contains('show'));

    await dna.handleMtDNAFile(textFile(jText, 'genome-mtdna.txt'));
    const mtConfirmReady = await waitFor(() => document.querySelector('[data-dna-action="confirm-mtdna-import"]') != null);
    overlay = document.getElementById('dna-modal-overlay');
    overlay?.querySelector<HTMLElement>('[data-dna-action="confirm-mtdna-import"]')?.click();
    const mtImportFinished = mtConfirmReady && await waitFor(() => state.importedData.genetics?.mtdna?.haplogroup === 'J' && calls.includes('navigate:dashboard'));
    check('confirmMtDNAImport stores mtdna', mtImportFinished);
    check('confirmMtDNAImport retains useful lineage and match detail',
      state.importedData.genetics?.mtdna?.origin &&
      state.importedData.genetics?.mtdna?.details &&
      Number.isFinite(state.importedData.genetics?.mtdna?.matchedMutations) &&
      state.importedData.genetics?.mtdna?.coupling?.description);
    const context = dna.buildGeneticsContext(state.importedData.genetics, null);
    check('mtDNA context includes mismatch detail', context.includes('mtDNA Haplogroup: J') && context.includes('ENVIRONMENT MISMATCH'));
    const rendered = dna.renderGeneticsSection();
    document.getElementById('fixture')!.innerHTML = rendered;
    check('renderGeneticsSection includes mtDNA card', document.querySelector('.genetics-mtdna-hg')?.textContent.includes('J'));
    check('renderGeneticsSection includes mtDNA lineage details',
      document.querySelector('.genetics-mtdna-facts')?.textContent.includes('Marker match') &&
      document.querySelector('.genetics-mtdna-detail')?.textContent!.length! > 0);
    check('mtDNA remove action is a semantic button', document.querySelector('[data-dna-action="delete-mtdna"]')?.tagName === 'BUTTON');

    document.querySelector<HTMLElement>('[data-dna-action="delete-mtdna"]')?.click();
    await wait();
    check('deleteMtDNAData removes mtdna only', state.importedData.genetics?.mtdna == null && state.importedData.genetics?.snps != null);

    await dna.setManualHaplogroup('bad');
    check('invalid manual haplogroup not stored', state.importedData.genetics?.mtdna == null);
    await dna.setManualHaplogroup('u5a');
    check('manual haplogroup preserves canonical mixed-case subclade', state.importedData.genetics?.mtdna?.haplogroup === 'U5a' && state.importedData.genetics.mtdna.source === 'manual');
    dna.ensureHaplogroupTable();
    check('haplogroup list exported', Array.isArray(dna.HAPLOGROUP_LIST) && dna.HAPLOGROUP_LIST.includes('J'));

    dnaRuntime.configureDnaRuntimeDeps(previousDnaRuntimeDeps);
    return { failures };
  });

  expect(results.failures).toEqual([]);
});

test('DNA genetics renderer covers empty and lazy-catalog branches', async ({ page }) => {
  await openBlankPage(page, '/dna-renderer-browser-coverage');

  const results = await page.evaluate(async () => {
    const failures: unknown[] = [];
    const check = (name: string, condition: unknown, detail = '') => {
      if (!condition) failures.push(detail ? `${name}: ${detail}` : name);
    };
    const wait = () => new Promise((resolve) => setTimeout(resolve, 0));
    const waitFor = async (predicate: () => unknown | Promise<unknown>) => {
      for (let i = 0; i < 100; i++) {
        if (predicate()) return true;
        await wait();
      }
      return false;
    };

    const { state } = await import('/js/state.js');
    const dna = (await import(`/js/dna.js?dnaRendererCoverage=${Date.now()}-${Math.random()}`) as unknown) as Pick<typeof import('../../js/dna.js'), "detectDNAFile" | "isDNAFile" | "isDNAFileByContent" | "getSnpCategoryLabel" | "parseDNAFile" | "findGenotypeInfo" | "findSnpHint" | "saveGeneticsData" | "buildFullGeneticsContext" | "buildGeneticsContext" | "deleteGeneticsData" | "ensureSNPTable" | "handleDNAFile" | "upsertGeneticsSnp" | "renderGeneticsSection" | "loadHaplogroupTable" | "parseMtDNAMutations" | "resolveHaplogroup" | "detectMtDNAMismatch" | "handleMtDNAFile" | "setManualHaplogroup" | "ensureHaplogroupTable" | "HAPLOGROUP_LIST">;
    const dnaRuntime = await import('/js/dna-runtime.js');
    const calls: unknown[] = [];
    const previousDnaRuntimeDeps = dnaRuntime.configureDnaRuntimeDeps({
      navigate: (route: unknown) => calls.push(route),
    });

    (state as { importedData: unknown }).importedData = { entries: [], notes: [], supplements: [], healthGoals: [], diagnoses: null, genetics: null, customMarkers: {}, markerNotes: {}, markerValueNotes: {}, changeHistory: [] };
    const emptyHtml = dna.renderGeneticsSection();
    check('empty renderer returns delegated upload stub',
      emptyHtml.includes('genetics-empty-stub') &&
      emptyHtml.includes('Add your DNA data') &&
      emptyHtml.includes('data-dna-action="import-file"') &&
      !emptyHtml.includes('onclick='));

    state.importedData.genetics = {
      source: 'Imported',
      importDate: '2026-06-09',
      coverage: { found: 1, total: 1 },
      effects: { moderate: 1 },
      snps: {
        rs1801133: { genotype: 'GA', gene: 'MTHFR', variant: 'C677T', category: 'methylation', effect: 'moderate', note: 'coverage note', markers: ['coagulation.homocysteine'] },
      },
    };
    const lazyHtml = dna.renderGeneticsSection();
    const lazyRefreshScheduled = await waitFor(() => calls.includes('dashboard'));
    check('lazy SNP table branch returns blank and schedules dashboard refresh', lazyHtml === '' && lazyRefreshScheduled);

    dnaRuntime.configureDnaRuntimeDeps(previousDnaRuntimeDeps);
    return { failures };
  });

  expect(results.failures).toEqual([]);
});

test('Genome lens widget exposes traits, structured mtDNA evidence, and privacy-safe contribution links', async ({ page }) => {
  await openBlankPage(page, '/genome-widget-evidence-coverage');

  const results = await page.evaluate(async () => {
    const failures: unknown[] = [];
    const check = (name: string, condition: unknown, detail = '') => {
      if (!condition) failures.push(detail ? `${name}: ${detail}` : name);
    };
    const { state } = await import('/js/state.js');
    const dna = (await import(`/js/dna.js?genomeWidgetCoverage=${Date.now()}-${Math.random()}`) as unknown) as Pick<typeof import('../../js/dna.js'), "detectDNAFile" | "isDNAFile" | "isDNAFileByContent" | "getSnpCategoryLabel" | "parseDNAFile" | "findGenotypeInfo" | "findSnpHint" | "saveGeneticsData" | "buildFullGeneticsContext" | "buildGeneticsContext" | "deleteGeneticsData" | "ensureSNPTable" | "handleDNAFile" | "upsertGeneticsSnp" | "renderGeneticsSection" | "loadHaplogroupTable" | "parseMtDNAMutations" | "resolveHaplogroup" | "detectMtDNAMismatch" | "handleMtDNAFile" | "setManualHaplogroup" | "ensureHaplogroupTable" | "HAPLOGROUP_LIST">;
    const { createDashboardWidgetRenderers } = (await import(`/js/dashboard-widget-renderers.js?genomeWidgetCoverage=${Date.now()}-${Math.random()}`) as unknown) as Pick<typeof import('../../js/dashboard-widget-renderers.js'), "createDashboardWidgetRenderers">;

    (state as { importedData: unknown }).importedData = {
      entries: [], notes: [], supplements: [], healthGoals: [], diagnoses: null,
      customMarkers: {}, markerNotes: {}, markerValueNotes: {}, changeHistory: [],
      genetics: {
        source: 'Living DNA',
        importDate: '2026-08-10',
        coverage: { found: 1, total: 60 },
        snps: {
          rs4680: { genotype: 'AA', gene: 'COMT', variant: 'Val158Met', category: 'neurotransmitters', effect: 'none', valence: 'informational' },
        },
        mtdna: {
          haplogroup: 'U5a', origin: 'European', source: 'mtDNA (Living DNA)',
          matchedMutations: 7, totalDiagnostic: 9, details: 'Stored maternal lineage detail.',
          coupling: {
            label: 'Moderately uncoupled', shortLabel: 'moderately uncoupled', climate: 'Temperate / Cold',
            description: 'Stored coupling description.', implications: 'Stored coupling implications.', matchedLatBands: [3, 4],
          },
        },
      },
    };
    await Promise.all([dna.ensureSNPTable(), dna.loadHaplogroupTable()]);

    const renderers = createDashboardWidgetRenderers({
      markerHasData: () => false,
      rerenderDashboardFromWidgetChange: () => {},
      showRecommendations: () => {},
    });
    document.body.innerHTML = `<main id="fixture">${renderers.renderDashboardGenomeWidget()}</main>`;

    check('informational COMT call is a visible blue trait',
      document.querySelector('.db-snp-trait')?.textContent.includes('COMT') &&
      document.querySelector('.db-genome-legend-trait')?.textContent.includes('trait'));
    check('SNP evidence drawer exposes primary evidence and a focused AI handoff',
      document.querySelector('[data-snp-evidence="rs4680"]') != null &&
      document.querySelector('[data-snp-evidence="rs4680"] .db-snp-evidence-source') != null &&
      document.querySelector('[data-snp-evidence="rs4680"] [data-dashboard-widget-action="ask-genome-snp"]') != null);
    check('SNP disclosure keeps strong evidence separate from trait-only relevance without row pills',
      document.querySelector('[data-snp-evidence="rs4680"] summary small')?.textContent.includes('Strong evidence') &&
      document.querySelector('[data-snp-evidence="rs4680"] summary small')?.textContent.includes('Trait only') &&
      document.querySelector('[data-snp-evidence="rs4680"]')?.closest('.db-snp-row')?.querySelector('.db-snp-axes') == null &&
      document.querySelector('[data-snp-evidence="rs4680"] .db-snp-interpretation')?.textContent.includes('What it supports') &&
      document.querySelector('[data-snp-evidence="rs4680"] .db-snp-interpretation')?.textContent.includes('Use in context') &&
      document.querySelector('[data-snp-evidence="rs4680"] .db-snp-evidence-grade') == null);
    check('mtDNA panel retains lineage, marker, coupling, and implication detail',
      document.querySelector('.db-mtdna-panel')?.textContent.includes('U5a') &&
      document.querySelector('.db-mtdna-panel')?.textContent.includes('7 / 9') &&
      document.querySelector('.db-mtdna-panel')?.textContent.includes('Stored coupling implications.'));
    check('mtDNA evidence represents supportive, mixed, and null evidence including the modern study',
      document.querySelectorAll('.db-mtdna-study').length >= 10 &&
      document.querySelector('.db-mtdna-study-supportive') != null &&
      document.querySelector('.db-mtdna-study-mixed') != null &&
      document.querySelector('.db-mtdna-study-null') != null &&
      document.querySelector('.db-mtdna-evidence')?.textContent.includes('41701624'));

    const snpCorrection = document.querySelector<HTMLAnchorElement>('[data-snp-evidence="rs4680"] .db-snp-correction-action');
    const mtCorrection = document.querySelector<HTMLAnchorElement>('.db-mtdna-evidence .db-genome-contribute-link');
    const snpBody = snpCorrection ? new URL(snpCorrection.href).searchParams.get('body') || '' : '';
    const mtBody = mtCorrection ? new URL(mtCorrection.href).searchParams.get('body') || '' : '';
    check('correction links disclose public workflow and exclude private calls',
      snpCorrection?.textContent.includes('correction') &&
      !snpBody.includes('**Genotype:**') &&
      !mtBody.includes('U5a') &&
      !mtBody.includes('European'));
    check('generic catalog contribution path is available',
      document.querySelector('.db-genome-contribute')?.textContent.includes('Suggest a SNP'));

    return { failures };
  });

  expect(results.failures).toEqual([]);
});
