// Small, independently enforced critical-behavior coverage gate.
// This supplements the complete CI denominator; it does not replace it.
import { defineConfig } from 'vitest/config';
import base from './vitest.config.js';
import { sourcePath } from './scripts/source-files.js';

export default defineConfig({
  ...base,
  test: {
    ...base.test!,
    include: [
      'tests/cycle-import-recovery.test.js',
      'tests/cycle-import-preview-recovery.test.js',
      'tests/cycle-import-storage-recovery.test.js',
      'tests/cycle-import-phase1.test.js',
      'tests/nutrition-editor-navigation.test.js',
      'tests/sun-session-recovery.test.js',
      'tests/sun-live-recovery.test.js',
      'tests/sun-session-format.test.js',
      'tests/sync-identity-vault-failures.test.js',
      'tests/sync-evolu8-identity-vault.test.js',
      'tests/profile-cleanup-failures.test.js',
      'tests/profile-cleanup-indexeddb.test.js',
      'tests/profile-storage-cleanup.test.js',
      'tests/sync-cleanup-boundaries.test.js',
      'tests/sync-evolu8-candidate.test.js',
      'tests/nutrition-request-lifecycle.test.js',
      'tests/nutrition-storage-boundaries.test.js',
      'tests/nutrition-store.test.js',
      'tests/nutrition-store-save-race.test.js',
      'tests/nutrition-store-recovery.test.ts',
      'tests/chat-history-reliability.test.js',
      'tests/chat-message-edit-reliability.test.js',
      'tests/chat-retry-reliability.test.js',
      'tests/hermes-gateway-client.test.js',
      'tests/hermes-gateway-lifecycle.test.js',
      'tests/hermes-gateway-registry.test.js',
      'tests/compat-proxy-server.test.js',
      'tests/compat-proxy-startup.test.js',
      'tests/agent-host-bootstrap.test.js',
      'tests/dev-agent-host.test.js',
      'tests/dev-agent-host-lifecycle.test.js',
      'tests/profile-share-server.test.js',
      'tests/profile-share-http-failures.test.js',
      'tests/profile-share-startup.test.js',
      'tests/profile-share-sqlite-store.test.js',
      'tests/profile-share-storage-failures.test.js',
      'tests/agent-process-lifecycle.test.js',
      'tests/agent-subprocess-lifecycle.test.js',
      'tests/agent-one-shot-failures.test.js',
      'tests/agent-private-files.test.js',
      'tests/claude-agent-client.test.js',
      'tests/openclaw-agent-client.test.js',
      'tests/agent-draft-claims.test.js',
      'tests/agent-draft-routing.test.js',
      'tests/agent-draft-persistence.test.js',
      'tests/agent-drafts.test.js',
      'tests/notes-safety.test.js',
      'tests/voice-local-tts-worker.test.ts',
      'tests/voice-local-stt-worker.test.ts',
      'tests/voice-stream-failures.test.ts',
      'tests/companion-http.test.js',
      'tests/companion-runtime-control.test.js',
      'tests/companion-listener.test.js',
      'tests/agent-rpc-failures.test.js',
      'tests/codex-app-server-client.test.js',
      'tests/acp-agent-client.test.js',
      'tests/service-worker-runtime.test.js',
      'tests/voice-player-failures.test.ts',
      'tests/voice-chat-runtime.test.js',
    ].map(file => sourcePath(file)),
    coverage: {
      ...base.test!.coverage!,
      enabled: true,
      include: [
        'js/cycle-import-mutations.js',
        'js/nutrition-editor-navigation.js',
        'js/sun-sessions-store.js',
        'js/sun-active-session-format.js',
        'js/sync-evolu8-identity-vault.js',
        'js/profile-storage-cleanup.js',
        'js/sync-disable-cleanup.js',
        'js/nutrition-request-lifecycle.js',
        'js/nutrition-store.js',
        'js/chat-history.js',
        'js/chat-message-edit.js',
        'lib/hermes-gateway-client.js',
        'server/compat-proxy-server.js',
        'server/agent-host-server.js',
        'lib/dev-agent-host.js',
        'server/profile-share-server.js',
        'lib/profile-share-sqlite-store.js',
        'js/agent-draft-claims.js', 'js/agent-drafts.js', 'js/notes.js',
        'js/voice-player.js',
        'js/voice-local-tts-worker.js',
        'js/voice-local-stt-worker.js',
        'lib/agent-process-lifecycle.js',
        'lib/claude-agent-client.js',
        'lib/openclaw-agent-client.js',
        'lib/acp-agent-client.js',
        'lib/codex-app-server-client.js',
        'lib/companion-http.js',
        'lib/companion-listener.js',
        'lib/companion-runtime-control.js',
        'service-worker-runtime.js',
      ],
      reportsDirectory: 'tests/.critical-coverage',
      reporter: ['json-summary', 'json', 'text'],
      thresholds: {
        'js/cycle-import-mutations.js': { lines: 97, functions: 95, branches: 83, statements: 92 },
        'js/nutrition-editor-navigation.js': { lines: 100, functions: 100, branches: 84, statements: 97 },
        'js/sun-sessions-store.js': { lines: 95, functions: 77, branches: 88, statements: 94 },
        'js/sun-active-session-format.js': { lines: 100, functions: 100, branches: 90, statements: 97 },
        'js/sync-evolu8-identity-vault.js': { lines: 94, functions: 88, branches: 88, statements: 93 },
        'js/profile-storage-cleanup.js': { lines: 100, functions: 100, branches: 88, statements: 98 },
        'js/sync-disable-cleanup.js': { lines: 100, functions: 100, branches: 100, statements: 100 },
        'js/nutrition-request-lifecycle.js': { lines: 91, functions: 51, branches: 94, statements: 91 },
        'js/nutrition-store.js': { lines: 89, functions: 80, branches: 73, statements: 84 },
        'js/chat-history.js': { lines: 99, functions: 88, branches: 92, statements: 96 },
        'js/chat-message-edit.js': { lines: 98, functions: 83, branches: 91, statements: 97 },
        'lib/hermes-gateway-client.js': { lines: 99, functions: 94, branches: 82, statements: 98 },
        'server/compat-proxy-server.js': { lines: 89, functions: 95, branches: 80, statements: 90 },
        'server/agent-host-server.js': { lines: 100, functions: 100, branches: 92, statements: 100 },
        'lib/dev-agent-host.js': { lines: 96, functions: 100, branches: 90, statements: 94 },
        'server/profile-share-server.js': { lines: 95, functions: 96, branches: 86, statements: 94 },
        'lib/profile-share-sqlite-store.js': { lines: 98, functions: 100, branches: 84, statements: 95 },
        'lib/agent-process-lifecycle.js': { lines: 100, functions: 91, branches: 100, statements: 100 },
        'lib/claude-agent-client.js': { lines: 100, functions: 100, branches: 91, statements: 100 },
        'lib/openclaw-agent-client.js': { lines: 96, functions: 90, branches: 84, statements: 93 },
        'js/voice-local-stt-worker.js': { lines: 98, functions: 83, branches: 91, statements: 99 },
        'js/voice-player.js': { lines: 92, functions: 87, branches: 74, statements: 88 },
        'js/voice-local-tts-worker.js': { lines: 99, functions: 90, branches: 95, statements: 99 },
        'lib/acp-agent-client.js': { lines: 95, functions: 87, branches: 83, statements: 90 },
        'lib/codex-app-server-client.js': { lines: 96, functions: 91, branches: 85, statements: 92 },
        'lib/companion-http.js': { lines: 100, functions: 100, branches: 93, statements: 100 },
        'lib/companion-listener.js': { lines: 100, functions: 100, branches: 100, statements: 100 },
        'lib/companion-runtime-control.js': { lines: 97, functions: 100, branches: 90, statements: 96 },
        'service-worker-runtime.js': { lines: 96, functions: 94, branches: 84, statements: 94 },
        'js/agent-draft-claims.js': { lines: 100, functions: 100, branches: 100, statements: 100 },
        'js/agent-drafts.js': { lines: 100, functions: 100, branches: 89, statements: 100 },
        'js/notes.js': { lines: 97, functions: 86, branches: 82, statements: 92 },
      },
    },
  },
});
