import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';
import type { ReferenceMarkerReader } from '../types/import-reference-benchmark.js';

// An unchecked reader for the generator's original JSON accesses.
type FixtureManifestReader = {expected: {markers: ReferenceMarkerReader[]}};

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = path.join(repoRoot, 'data', 'import-benchmark-reference-us-v2.gold.json');
const outputPath = path.join(repoRoot, 'data', 'import-benchmark-reference-us-v2.pdf');
const manifest: FixtureManifestReader = JSON.parse(await fs.readFile(manifestPath, 'utf8'));

function escapeHTML(value: unknown) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function markerFlag(marker: ReferenceMarkerReader) {
  if (Number(marker.value) < Number(marker.refMin)) return 'LOW';
  if (Number(marker.value) > Number(marker.refMax)) return 'HIGH';
  return '';
}

function renderSection(title: unknown, markers: readonly ReferenceMarkerReader[]) {
  const rows = markers.map(marker => {
    const flag = markerFlag(marker);
    return `<tr>
      <td>${escapeHTML(marker.rawName)}</td>
      <td class="number">${escapeHTML(marker.value)}</td>
      <td class="flag ${flag.toLowerCase()}">${flag}</td>
      <td>${escapeHTML(marker.unit || '—')}</td>
      <td>${escapeHTML(marker.refMin)} – ${escapeHTML(marker.refMax)}</td>
    </tr>`;
  }).join('');
  return `<section>
    <h2>${escapeHTML(title)}</h2>
    <table>
      <thead><tr><th>Test</th><th>Result</th><th>Flag</th><th>Units</th><th>Reference interval</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </section>`;
}

function renderPage(pageNumber: number) {
  const pageMarkers = manifest.expected.markers.filter(marker => marker.page === pageNumber);
  const sections: Array<{title: unknown; markers: ReferenceMarkerReader[]}> = [];
  for (const marker of pageMarkers) {
    let section = sections.find(item => item.title === marker.section);
    if (!section) {
      section = { title: marker.section, markers: [] };
      sections.push(section);
    }
    section.markers.push(marker);
  }
  return `<article class="report-page">
    <header>
      <div>
        <div class="lab-name">NORTHSTAR DIAGNOSTIC LABORATORY</div>
        <div class="lab-subtitle">Comprehensive Health Reference Report</div>
      </div>
      <div class="report-meta"><strong>FINAL REPORT</strong><br>Accession: GB-REF-US-260714</div>
    </header>
    <div class="fixture-warning">REFERENCE FIXTURE ONLY — NOT A REAL PATIENT OR LABORATORY REPORT</div>
    <div class="patient-grid">
      <div><span>Patient</span><strong>BENCHMARK SAMPLE</strong></div>
      <div><span>Date of birth</span><strong>01/01/1990</strong></div>
      <div><span>Specimen</span><strong>Serum / EDTA whole blood</strong></div>
      <div><span>Collected</span><strong>07/14/2026 08:15</strong></div>
      <div><span>Received</span><strong>07/14/2026 13:42</strong></div>
      <div><span>Reported</span><strong>07/15/2026 11:30</strong></div>
    </div>
    ${sections.map(section => renderSection(section.title, section.markers)).join('')}
    <footer>
      <span>Synthetic educational fixture generated by getbased. No clinical use.</span>
      <span>Page ${pageNumber} of 3</span>
    </footer>
  </article>`;
}

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><style>
  @page { size: Letter; margin: 0; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #fff; color: #182235; font-family: Arial, Helvetica, sans-serif; }
  .report-page { position: relative; width: 8.5in; height: 11in; padding: .38in .45in .48in; break-after: page; overflow: hidden; }
  .report-page:last-child { break-after: auto; }
  header { display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 9px; border-bottom: 3px solid #174f78; }
  .lab-name { color: #174f78; font-size: 16px; font-weight: 800; letter-spacing: .055em; }
  .lab-subtitle { margin-top: 2px; color: #526476; font-size: 9px; }
  .report-meta { color: #526476; font-size: 8px; line-height: 1.45; text-align: right; }
  .report-meta strong { color: #174f78; font-size: 10px; }
  .fixture-warning { margin: 8px 0; padding: 5px; border: 1px solid #d18b26; background: #fff7e7; color: #8a5508; font-size: 8px; font-weight: 800; letter-spacing: .08em; text-align: center; }
  .patient-grid { display: grid; grid-template-columns: 1.15fr 1fr 1.4fr; gap: 5px 12px; margin-bottom: 9px; padding: 7px 9px; background: #f0f4f7; }
  .patient-grid span, .patient-grid strong { display: block; }
  .patient-grid span { color: #6d7c89; font-size: 6.5px; letter-spacing: .05em; text-transform: uppercase; }
  .patient-grid strong { margin-top: 1px; color: #223345; font-size: 8px; }
  section { margin-top: 8px; break-inside: avoid; }
  h2 { margin: 0; padding: 4px 7px; background: #174f78; color: white; font-size: 8.5px; letter-spacing: .055em; text-transform: uppercase; }
  table { width: 100%; border-collapse: collapse; table-layout: fixed; }
  th, td { padding: 3px 6px; border-bottom: .5px solid #cad3da; font-size: 7.5px; line-height: 1.15; text-align: left; }
  th { background: #e9eef2; color: #4b5e6f; font-size: 6.5px; letter-spacing: .04em; text-transform: uppercase; }
  th:nth-child(1) { width: 35%; }
  th:nth-child(2) { width: 13%; }
  th:nth-child(3) { width: 10%; }
  th:nth-child(4) { width: 18%; }
  th:nth-child(5) { width: 24%; }
  td.number { font-weight: 700; }
  td.flag { color: #9b1c1c; font-size: 6.5px; font-weight: 800; }
  tbody tr:nth-child(even) { background: #f8fafb; }
  footer { position: absolute; right: .45in; bottom: .22in; left: .45in; display: flex; justify-content: space-between; padding-top: 5px; border-top: .5px solid #9eabb6; color: #6d7c89; font-size: 6.5px; }
</style></head><body>${[1, 2, 3].map(renderPage).join('')}</body></html>`;

const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
try {
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'load' });
  await page.pdf({ path: outputPath, format: 'Letter', printBackground: true, preferCSSPageSize: true });
} finally {
  await browser.close();
}

console.log(`Generated ${path.relative(repoRoot, outputPath)} with ${manifest.expected.markers.length} gold markers.`);
