import type { MarkerCategory } from './types.js';

// Stable built-in calculated ratios marker category.
// Reference sources: Fest et al. 2018 (PMCID PMC6043609) for NLR/PLR/SII;
// Buttle et al. 2021 (PMCID PMC8405018) for MLR; Li et al. 2025
// (DOI 10.3389/fnut.2025.1580904) for hs-CRP/HDL-C;
// AASLD 2023 practice guidance (PMID 36727674) for FIB-4; PMID 40087045 for
// sex-aware TyG risk cutoffs; NHIS/NCHS Series 2 No. 210 for A/G; and PMID
// 11369334 for the representative modern anion gap.

export const CALCULATED_RATIOS_CATEGORY = {
  label: "Calculated Ratios", icon: "\uD83D\uDCD0", calculated: true,
  markers: {
    tgHdlRatio: { name: "TG/HDL Ratio", unit: "", refMin: 0, refMax: 1.75, desc: "Triglycerides divided by HDL; a strong surrogate marker for insulin resistance and small dense LDL particles." },
    ldlHdlRatio: { name: "LDL/HDL Ratio", unit: "", refMin: 0, refMax: 2.5, refMax_f: 2.0, desc: "Balance of atherogenic to protective cholesterol; a simple predictor of coronary heart disease risk." },
    apoBapoAIRatio: { name: "ApoB/ApoA-I Ratio", unit: "", refMin: 0, refMax: 0.9, refMax_f: 0.8, desc: "Ratio of atherogenic to protective lipoprotein particles; considered the best single lipid marker for cardiovascular risk." },
    cholHdlRatio: { name: "Total Cholesterol/HDL Ratio", unit: "", refMin: 0, refMax: 5.0, desc: "Total cholesterol divided by HDL; a simple cardiovascular risk ratio where lower values are generally better." },
    nlr: { name: "Neutrophil-Lymphocyte Ratio (NLR)", unit: "", refMin: 0.83, refMax: 3.92, refMin_f: 0.8, refMax_f: 3.8, rangePolicy: "guidance", desc: "A marker of systemic inflammation and immune stress. The displayed reference uses population 95% intervals (sex- and, from age 45, age-aware); acute illness and clinical context still matter." },
    plr: { name: "Platelet-Lymphocyte Ratio (PLR)", unit: "", refMin: 61, refMax: 239, refMin_f: 65, refMax_f: 246, rangePolicy: "guidance", desc: "Reflects the balance between thrombotic and immune responses. The displayed reference uses population 95% intervals (sex- and, from age 45, age-aware), not a disease-specific cutoff." },
    mlr: { name: "Monocyte-Lymphocyte Ratio (MLR)", unit: "", refMin: 0.14, refMax: 0.51, refMin_f: 0.12, refMax_f: 0.47, rangePolicy: "guidance", desc: "Monocytes divided by lymphocytes; a simple immune-balance and inflammation marker. The displayed sex-specific reference is a healthy-adult population interval, not a diagnosis or disease-specific cutoff." },
    deRitisRatio: { name: "De Ritis Ratio (AST/ALT)", unit: "", refMin: 0.8, refMax: 1.2, desc: "AST divided by ALT; helps distinguish liver damage types \u2014 values above 2 suggest alcoholic liver disease or cirrhosis." },
    copperZincRatio: { name: "Copper/Zinc Ratio", unit: "", refMin: 0.7, refMax: 1.0, desc: "Balance between copper and zinc; elevated ratios indicate oxidative stress, inflammation, or immune dysfunction." },
    ft3ft4Ratio: { name: "Free T3/Free T4 Ratio", unit: "", refMin: 0.262, refMax: 0.346, desc: "Compares active Free T3 with its Free T4 precursor; helps show whether circulating thyroid hormone balance is relatively T3- or T4-dominant and should be read alongside TSH and the individual hormone values." },
    bunCreatRatio: { name: "BUN/Creatinine Ratio", unit: "", refMin: 10, refMax: 20, desc: "Blood urea nitrogen divided by creatinine; helps differentiate pre-renal, renal, and post-renal causes of kidney dysfunction." },
    freeWaterDeficit: { name: "Free Water Deficit", unit: "L", refMin: 0, refMax: 0, rangePolicy: "target", desc: "Estimated from sodium, sex, and the latest available body weight using a formula intended mainly for hypernatremia. Zero is the target. A positive value estimates liters of free water missing relative to the sodium target; a negative value does not mean dehydration and is only an algebraic water-excess or low-sodium signal, not a diagnosis of overhydration. Interpret either direction with sodium and clinical volume context." },
    crpHdlRatio: { name: "hs-CRP/HDL-C Ratio", unit: "", refMin: 0, refMax: 0.05, rangePolicy: "guidance", desc: "Calculated as hs-CRP (mg/L) divided by HDL-C (mg/dL). The optional 0–0.02 band covers the lower half of a large longitudinal middle-aged and older cohort, while 0.05 marks its highest quartile; these are population risk guides, not universal clinical cutoffs. Requires hs-CRP specifically." },
    atherogenicIndexPlasma: { name: "Atherogenic Index of Plasma (AIP)", unit: "", refMin: null, refMax: 0.21, rangePolicy: "guidance", desc: "Base-10 logarithm of the molar triglyceride-to-HDL ratio. Proposed bands are below 0.11 lower risk, 0.11–0.21 intermediate, and above 0.21 higher risk; this is risk guidance, not a diagnosis." },
    tygIndex: { name: "Triglyceride-Glucose Index (TyG)", unit: "", refMin: null, refMax: 8.8, refMax_f: 8.6, rangePolicy: "guidance", desc: "Natural logarithm of fasting triglycerides × fasting glucose in mg/dL divided by 2; a surrogate for insulin resistance. The optional lower-risk ceiling of 8.6 follows a cohort dose-response meta-analysis, while sex-aware reference guidance varies by population; all ranges are suppressed for a known non-fasting sample." },
    albuminGlobulinRatio: { name: "Albumin/Globulin Ratio", unit: "", refMin: 1.0, refMax: 2.5, rangePolicy: "guidance", desc: "Albumin divided by globulin, using measured globulin when available or total protein minus albumin. The displayed 1.0–2.5 interval is a common adult laboratory reference; the reporting laboratory and individual protein values take priority." },
    fib4Index: { name: "FIB-4 Index", unit: "", refMin: 0, refMax: 1.3, rangePolicy: "guidance", desc: "Age, AST, ALT, and platelets combined to screen for advanced liver fibrosis. The displayed AASLD thresholds use below 1.3 for ages 35–64 and below 2.0 after age 65; it is not validated under 35 or during acute illness, and above 2.67 is higher risk." },
    systemicImmuneInflammationIndex: { name: "Systemic Immune-Inflammation Index (SII)", unit: "10^9/l", refMin: 189, refMax: 1168, refMin_f: 194, refMax_f: 1169, rangePolicy: "guidance", desc: "Platelets × neutrophils divided by lymphocytes. The displayed sex- and age-aware reference uses general-population 95% intervals, not a universal disease cutoff, and is sensitive to acute illness." },
    anionGap: { name: "Anion Gap", unit: "mmol/l", refMin: 5, refMax: 12, rangePolicy: "guidance", desc: "Sodium minus chloride and bicarbonate, without potassium. The displayed 5–12 interval is representative guidance for ion-selective-electrode methods; analyzer, albumin, and the reporting laboratory's interval take priority." },
    phenoAge: { name: "PhenoAge", unit: "years", refMin: null, refMax: null, rangePolicy: "contextual", hidden: true, desc: "Biological age from 9 biomarkers using the Levine 2018 mortality-calibrated formula; its comparison value is chronological age rather than a fixed population interval." },
    bortzAge: { name: "Bortz Age", unit: "years", refMin: null, refMax: null, rangePolicy: "contextual", hidden: true, desc: "Biological age from 22 biomarkers using the Bortz 2023 aging-acceleration model; its comparison value is chronological age rather than a fixed population interval." },
    biologicalAge: { name: "Biological Age", unit: "years", refMin: null, refMax: null, rangePolicy: "contextual", desc: "Combined biological age from PhenoAge (Levine 2018, 9 markers) and Bortz Age (Bortz 2023, 22 markers). Compare it with chronological age rather than a fixed population interval; lower is generally favorable." }
  }
} satisfies MarkerCategory;
