import type { MarkerCategory } from './types.js';

// Stable built-in hormones marker category.

export const HORMONES_CATEGORY = {
  label: "Hormones", icon: "\uD83E\uDDEC",
  markers: {
    testosterone: { name: "Testosterone", unit: "nmol/l", refMin: 8.64, refMax: 29.00, refMin_f: 0.29, refMax_f: 1.67, desc: "The primary androgen, important for muscle, bone, sexual function, and wellbeing in both sexes. The optional adult wellness band is sex-specific; for men aged 70–89, a narrower lower-mortality cohort band is shown as observational guidance, not a testosterone-therapy target." },
    freeTestosterone: { name: "Free Testosterone", unit: "pmol/l", refMin: 30.70, refMax: 161.70, refMin_f: 0.30, refMax_f: 10.40, desc: "The unbound, biologically active fraction of testosterone; a better indicator of androgen status than total testosterone." },
    freeTestosteronePercentage: { name: "Free Testosterone %", unit: "%", refMin: 1.53, refMax: 2.88, desc: "The proportion of total testosterone that is entirely unbound in blood; an excellent metric for monitoring true androgen availability." },
    shbg: { name: "SHBG", unit: "nmol/l", refMin: 14.5, refMax: 54.1, refMin_f: 26.1, refMax_f: 110.0, desc: "A protein that binds sex hormones and regulates their availability; high levels reduce free testosterone." },
    dheaS: { name: "DHEA-S", unit: "\u00b5mol/l", refMin: 2.41, refMax: 11.60, refMin_f: 1.77, refMax_f: 9.22, desc: "An adrenal androgen precursor that declines substantially with age. When age and sex are available, the dashboard uses an assay-specific adult reference band; there is no validated universal wellness optimum, and the reporting laboratory remains authoritative." },
    fai: { name: "Free Androgen Index", unit: "%", refMin: 34.0, refMax: 106.0, refMin_f: 0.5, refMax_f: 6.9, desc: "Ratio of total testosterone to SHBG; estimates bioavailable androgen activity, useful for detecting hormonal imbalances." },
    estradiol: { name: "Estradiol", unit: "pmol/l", refMin: 41.4, refMax: 159.0, refMin_f: 45.4, refMax_f: 854.0, desc: "The primary estrogen hormone; essential for bone health, cardiovascular protection, and reproductive function. For regular natural cycles, the app can show an assay-specific range for the calendar-predicted phase; the reporting laboratory and assay remain authoritative." },
    progesterone: { name: "Progesterone", unit: "nmol/l", refMin: 0.159, refMax: 0.474, refMin_f: 0.181, refMax_f: 27.0, desc: "A hormone supporting pregnancy and menstrual cycle regulation. For regular natural cycles, the app can show an assay-specific range for the calendar-predicted phase; the reporting laboratory and assay remain authoritative." },
    pth: { name: "Parathyroid Hormone (PTH)", unit: "pmol/l", refMin: 1.6, refMax: 6.9, desc: "Regulates calcium and phosphorus balance; interpret alongside calcium, vitamin D, and kidney function because reference ranges vary by assay and laboratory." },
    calcitonin: { name: "Calcitonin", unit: "ng/l", refMin: 1.0, refMax: 11.8, refMin_f: 1.0, refMax_f: 4.6, desc: "A thyroid hormone that lowers blood calcium; used as a tumor marker for medullary thyroid carcinoma." },
    dht: { name: "DHT", unit: "nmol/l", refMin: 0.86, refMax: 3.40, refMin_f: 0.12, refMax_f: 0.86, desc: "A potent androgen converted from testosterone; drives male-pattern hair loss and prostate growth." },
    igf1: { name: "IGF-1", unit: "\u00b5g/l", refMin: 96.4, refMax: 227.8, desc: "A growth-factor hormone mediating growth-hormone effects. Reference interpretation is age-, sex-, and assay-specific; the optional 120–160 µg/l wellness band comes from general-population mortality research and is not a treatment target or substitute for an IGF-1 Z-score." },
    cortisol: { name: "Cortisol", unit: "nmol/l", refMin: 140, refMax: 620, desc: "Primary glucocorticoid stress hormone. A known morning or afternoon collection time selects a corresponding serum assay range; an isolated result outside ordinary collection windows is left to the lab and clinical context rather than assigned a generic wellness target." },
    acth: { name: "ACTH", unit: "pmol/l", refMin: 1.6, refMax: 13.9, desc: "Pituitary hormone stimulating adrenal cortisol production. This representative interval is for a 07:00\u201310:00 draw; interpret with cortisol, collection time, specimen handling, and the reporting laboratory's interval." },
    aldosterone: { name: "Aldosterone", unit: "pmol/l", refMin: 0, refMax: 583, desc: "Adrenal mineralocorticoid regulating sodium, potassium, and blood pressure. This representative adult interval is for a morning peripheral sample; posture, sodium intake, medications, and collection time strongly affect interpretation." },
    renin: { name: "Renin", unit: "mU/l", refMin: 5.4, refMax: 60, desc: "Direct renin concentration used with aldosterone; this broad adult interval includes upright sampling. Concentration and activity assays are not interchangeable, and posture and method-specific laboratory ranges take priority." },
    amh: { name: "Anti-M\u00fcllerian Hormone (AMH)", unit: "pmol/l", refMin: 0, refMax: 92.9, refMin_f: 0, refMax_f: 85.7, desc: "Gonadal hormone used mainly for ovarian-reserve and reproductive assessment. Women aged 20+ receive an age-specific assay reference band when no lab interval was imported; assays are not interchangeable and no universal fertility or wellness optimum is claimed." },
    androstenedione: { name: "Androstenedione", unit: "nmol/l", refMin: 1.4, refMax: 7.4, refMin_f: 1.0, refMax_f: 11.5, desc: "Androgen precursor made by adrenals and gonads; useful for androgen-excess and steroid-pathway context." },
    lh: { name: "LH", unit: "U/l", refMin: 1.7, refMax: 8.6, refMin_f: 2.4, refMax_f: 12.6, desc: "Luteinizing hormone; triggers ovulation in women and stimulates testosterone production in men. It surges mid-cycle and is secreted in pulses, so a single result and a calendar-predicted phase need laboratory and clinical context." },
    fsh: { name: "FSH", unit: "U/l", refMin: 1.5, refMax: 12.4, refMin_f: 3.5, refMax_f: 12.5, desc: "Follicle-stimulating hormone; drives egg maturation in women and sperm production in men. It varies across the cycle, is secreted in pulses, and rises after menopause, so a single result needs laboratory and clinical context." },
    prolactin: { name: "Prolactin", unit: "\u00b5g/l", refMin: 4.0, refMax: 15.2, refMin_f: 4.8, refMax_f: 23.3, desc: "Stimulates milk production; elevated levels can suppress ovulation and indicate pituitary issues." },
    bioactiveTestosterone: { name: "Bioactive Testosterone", unit: "nmol/l", refMin: 4.37, refMax: 14.3, refMin_f: 0.05, refMax_f: 0.60, desc: "The sum of free and weakly albumin-bound testosterone; ready to be utilized by tissues, making it a powerful indicator of bioavailable androgen status." },
    bioactiveTestosteronePercentage: { name: "Bioactive Testosterone %", unit: "%", refMin: 35.0, refMax: 66.3, desc: "The proportion of total testosterone that is biologically active; helps evaluate hormonal availability when SHBG is abnormal." },
    hCG: { name: "hCG (Chorionic Gonadotropin)", unit: "U/l", refMin: 0.0, refMax: 2.5, desc: "Human chorionic gonadotropin; a hormone produced during pregnancy and also utilized as a highly specific biomarker for certain reproductive conditions." }
  }
} satisfies MarkerCategory;
