import type { MarkerIdentityRow } from './types.js';

// marker-schema/identities.js — Stable built-in marker identities.
//
// Identity keys are immutable. Moving or renaming a marker changes only its
// current dotKey; the previous dotKey must be retained in legacyDotKeys.

const BUILTIN_MARKER_ID_PREFIX = 'gb:marker:';


const IDENTITY_ROWS: MarkerIdentityRow[] = [
  ['glucose', 'biochemistry.glucose'],
  ['urea', 'biochemistry.urea'],
  ['creatinine', 'biochemistry.creatinine'],
  ['egfr', 'biochemistry.egfr'],
  ['egfrCombined', 'biochemistry.egfrCombined', ['biochemistry.egfrCreatinineCystatinC']],
  ['uricAcid', 'biochemistry.uricAcid'],
  ['bilirubinTotal', 'biochemistry.bilirubinTotal'],
  ['bilirubinDirect', 'biochemistry.bilirubinDirect'],
  ['bilirubinIndirect', 'biochemistry.bilirubinIndirect'],
  ['bicarbonate', 'biochemistry.bicarbonate'],
  ['ast', 'biochemistry.ast'],
  ['alt', 'biochemistry.alt'],
  ['alp', 'biochemistry.alp'],
  ['ggt', 'biochemistry.ggt'],
  ['ldh', 'biochemistry.ldh'],
  ['creatineKinase', 'biochemistry.creatineKinase'],
  ['amylase', 'biochemistry.amylase'],
  ['lipase', 'biochemistry.lipase'],
  ['osmolality', 'biochemistry.osmolality'],
  ['lactate', 'biochemistry.lactate'],
  ['pyruvate', 'biochemistry.pyruvate'],
  ['cystatinC', 'biochemistry.cystatinC'],
  ['gfrCystatin', 'biochemistry.gfrCystatin'],
  ['testosterone', 'hormones.testosterone'],
  ['freeTestosterone', 'hormones.freeTestosterone'],
  ['freeTestosteronePercentage', 'hormones.freeTestosteronePercentage'],
  ['shbg', 'hormones.shbg'],
  ['dheaS', 'hormones.dheaS'],
  ['fai', 'hormones.fai'],
  ['estradiol', 'hormones.estradiol'],
  ['progesterone', 'hormones.progesterone'],
  ['pth', 'hormones.pth'],
  ['calcitonin', 'hormones.calcitonin'],
  ['dht', 'hormones.dht'],
  ['igf1', 'hormones.igf1'],
  ['cortisol', 'hormones.cortisol'],
  ['acth', 'hormones.acth'],
  ['aldosterone', 'hormones.aldosterone'],
  ['renin', 'hormones.renin'],
  ['amh', 'hormones.amh'],
  ['androstenedione', 'hormones.androstenedione'],
  ['lh', 'hormones.lh'],
  ['fsh', 'hormones.fsh'],
  ['prolactin', 'hormones.prolactin'],
  ['bioactiveTestosterone', 'hormones.bioactiveTestosterone'],
  ['bioactiveTestosteronePercentage', 'hormones.bioactiveTestosteronePercentage'],
  ['hCG', 'hormones.hCG'],
  ['sodium', 'electrolytes.sodium'],
  ['potassium', 'electrolytes.potassium'],
  ['chloride', 'electrolytes.chloride'],
  ['calciumTotal', 'electrolytes.calciumTotal'],
  ['calciumIonized', 'electrolytes.calciumIonized'],
  ['phosphorus', 'electrolytes.phosphorus'],
  ['magnesium', 'electrolytes.magnesium'],
  ['magnesiumRBC', 'electrolytes.magnesiumRBC'],
  ['copper', 'electrolytes.copper'],
  ['zinc', 'electrolytes.zinc'],
  ['selenium', 'electrolytes.selenium'],
  ['cholesterol', 'lipids.cholesterol', [
    'lipids.totalCholesterol',
    'lipids.cholesterolTotal',
    'lipids.total_cholesterol',
    'lipids.totalChol',
  ]],
  ['triglycerides', 'lipids.triglycerides'],
  ['hdl', 'lipids.hdl', ['lipids.hdlCholesterol', 'lipids.hdl_cholesterol']],
  ['ldl', 'lipids.ldl'],
  ['nonHdl', 'lipids.nonHdl'],
  ['apoAI', 'lipids.apoAI'],
  ['apoB', 'lipids.apoB'],
  ['lpA', 'lipids.lpA', [
    'lipids.lpa',
    'lipids.lp_a',
    'lipids.lipoproteinA',
    'lipids.lipoproteina',
  ]],
  ['iron', 'iron.iron'],
  ['ferritin', 'iron.ferritin'],
  ['transferrin', 'iron.transferrin'],
  ['tibc', 'iron.tibc'],
  ['transferrinSat', 'iron.transferrinSat'],
  ['solubleTransferrinReceptor', 'iron.solubleTransferrinReceptor'],
  ['hsCRP', 'proteins.hsCRP'],
  ['crp', 'proteins.crp'],
  ['totalProtein', 'proteins.totalProtein'],
  ['albumin', 'proteins.albumin'],
  ['globulin', 'proteins.globulin'],
  ['esr', 'proteins.esr'],
  ['ceruloplasmin', 'proteins.ceruloplasmin'],
  ['neurofilamentLight', 'proteins.neurofilamentLight'],
  ['tsh', 'thyroid.tsh'],
  ['ft4', 'thyroid.ft4'],
  ['ft3', 'thyroid.ft3'],
  ['t4total', 'thyroid.t4total'],
  ['t3total', 'thyroid.t3total'],
  ['reverseT3', 'thyroid.reverseT3'],
  ['tpoAb', 'thyroid.tpoAb'],
  ['tgAb', 'thyroid.tgAb'],
  ['trab', 'thyroid.trab'],
  ['thyroglobulin', 'thyroid.thyroglobulin'],
  ['vitaminD', 'vitamins.vitaminD'],
  ['vitaminD3', 'vitamins.vitaminD3'],
  ['calcitriol', 'vitamins.calcitriol'],
  ['vitaminA', 'vitamins.vitaminA'],
  ['vitaminB12', 'vitamins.vitaminB12'],
  ['activeB12', 'vitamins.activeB12'],
  ['methylmalonicAcid', 'vitamins.methylmalonicAcid'],
  ['folate', 'vitamins.folate'],
  ['vitaminB1', 'vitamins.vitaminB1'],
  ['vitaminB6', 'vitamins.vitaminB6'],
  ['vitaminC', 'vitamins.vitaminC'],
  ['vitaminE', 'vitamins.vitaminE'],
  ['hba1c', 'diabetes.hba1c'],
  ['insulin', 'diabetes.insulin', ['hormones.insulin', 'diabetes.insulin_d'], ['insulin_d']],
  ['cPeptide', 'diabetes.cPeptide', ['hormones.cPeptide']],
  ['fructosamine', 'diabetes.fructosamine'],
  ['homaIR', 'diabetes.homaIR'],
  ['psa', 'tumorMarkers.psa'],
  ['afp', 'tumorMarkers.afp'],
  ['cea', 'tumorMarkers.cea'],
  ['ca125', 'tumorMarkers.ca125'],
  ['ca199', 'tumorMarkers.ca199'],
  ['ca153', 'tumorMarkers.ca153'],
  ['homocysteine', 'coagulation.homocysteine'],
  ['pt', 'coagulation.pt'],
  ['inr', 'coagulation.inr'],
  ['aptt', 'coagulation.aptt'],
  ['fibrinogen', 'coagulation.fibrinogen'],
  ['dDimer', 'coagulation.dDimer'],
  ['wbc', 'hematology.wbc'],
  ['rbc', 'hematology.rbc'],
  ['hemoglobin', 'hematology.hemoglobin'],
  ['hematocrit', 'hematology.hematocrit'],
  ['mcv', 'hematology.mcv'],
  ['mch', 'hematology.mch'],
  ['mchc', 'hematology.mchc'],
  ['rdwcv', 'hematology.rdwcv'],
  ['platelets', 'hematology.platelets'],
  ['mpv', 'hematology.mpv'],
  ['pdw', 'hematology.pdw'],
  ['pct', 'hematology.pct'],
  ['reticulocytes', 'hematology.reticulocytes'],
  ['reticulocytesPct', 'hematology.reticulocytesPct'],
  ['immatureGranulocytes', 'hematology.immatureGranulocytes'],
  ['immatureGranulocytesPct', 'hematology.immatureGranulocytesPct'],
  ['neutrophils', 'differential.neutrophils'],
  ['lymphocytes', 'differential.lymphocytes'],
  ['monocytes', 'differential.monocytes'],
  ['eosinophils', 'differential.eosinophils'],
  ['basophils', 'differential.basophils'],
  ['neutrophilsPct', 'differential.neutrophilsPct'],
  ['lymphocytesPct', 'differential.lymphocytesPct'],
  ['monocytesPct', 'differential.monocytesPct'],
  ['eosinophilsPct', 'differential.eosinophilsPct'],
  ['basophilsPct', 'differential.basophilsPct'],
  ['osteocalcin', 'boneMetabolism.osteocalcin'],
  ['p1np', 'boneMetabolism.p1np'],
  ['ctx', 'boneMetabolism.ctx'],
  ['ph', 'urinalysis.ph'],
  ['specificGravity', 'urinalysis.specificGravity'],
  ['urineAlbumin', 'urinalysis.albumin'],
  ['urineCreatinine', 'urinalysis.creatinine'],
  ['albuminCreatinineRatio', 'urinalysis.albuminCreatinineRatio'],
  ['urineTotalProtein', 'urinalysis.totalProtein'],
  ['proteinCreatinineRatio', 'urinalysis.proteinCreatinineRatio'],
  ['hsTroponinT', 'cardiac.hsTroponinT'],
  ['hsTroponinI', 'cardiac.hsTroponinI'],
  ['bnp', 'cardiac.bnp'],
  ['ntProBnp', 'cardiac.ntProBnp'],
  ['bodyFatPct', 'bodyComposition.bodyFatPct'],
  ['leanMass', 'bodyComposition.leanMass'],
  ['fatMass', 'bodyComposition.fatMass'],
  ['bmiDexa', 'bodyComposition.bmiDexa'],
  ['androidFatPct', 'bodyComposition.androidFatPct'],
  ['gynoidFatPct', 'bodyComposition.gynoidFatPct'],
  ['agRatio', 'bodyComposition.agRatio'],
  ['visceralFatArea', 'bodyComposition.visceralFatArea'],
  ['bmdSpine', 'boneDensity.bmdSpine'],
  ['bmdFemurTotal', 'boneDensity.bmdFemurTotal'],
  ['bmdFemurNeck', 'boneDensity.bmdFemurNeck'],
  ['tScoreSpine', 'boneDensity.tScoreSpine'],
  ['tScoreFemurTotal', 'boneDensity.tScoreFemurTotal'],
  ['tScoreFemurNeck', 'boneDensity.tScoreFemurNeck'],
  ['zScoreSpine', 'boneDensity.zScoreSpine'],
  ['zScoreFemurTotal', 'boneDensity.zScoreFemurTotal'],
  ['zScoreFemurNeck', 'boneDensity.zScoreFemurNeck'],
  ['tgHdlRatio', 'calculatedRatios.tgHdlRatio'],
  ['ldlHdlRatio', 'calculatedRatios.ldlHdlRatio'],
  ['apoBapoAIRatio', 'calculatedRatios.apoBapoAIRatio'],
  ['cholHdlRatio', 'calculatedRatios.cholHdlRatio', ['lipids.cholHdlRatio']],
  ['nlr', 'calculatedRatios.nlr'],
  ['plr', 'calculatedRatios.plr'],
  ['mlr', 'calculatedRatios.mlr'],
  ['deRitisRatio', 'calculatedRatios.deRitisRatio'],
  ['copperZincRatio', 'calculatedRatios.copperZincRatio'],
  ['ft3ft4Ratio', 'calculatedRatios.ft3ft4Ratio'],
  ['bunCreatRatio', 'calculatedRatios.bunCreatRatio'],
  ['freeWaterDeficit', 'calculatedRatios.freeWaterDeficit'],
  ['crpHdlRatio', 'calculatedRatios.crpHdlRatio'],
  ['atherogenicIndexPlasma', 'calculatedRatios.atherogenicIndexPlasma'],
  ['tygIndex', 'calculatedRatios.tygIndex'],
  ['albuminGlobulinRatio', 'calculatedRatios.albuminGlobulinRatio'],
  ['fib4Index', 'calculatedRatios.fib4Index'],
  ['systemicImmuneInflammationIndex', 'calculatedRatios.systemicImmuneInflammationIndex'],
  ['anionGap', 'calculatedRatios.anionGap'],
  ['phenoAge', 'calculatedRatios.phenoAge'],
  ['bortzAge', 'calculatedRatios.bortzAge'],
  ['biologicalAge', 'calculatedRatios.biologicalAge'],
];

for (const row of IDENTITY_ROWS) {
  if (row[2]) Object.freeze(row[2]);
  if (row[3]) Object.freeze(row[3]);
  Object.freeze(row);
}

const BUILTIN_MARKER_IDENTITY_ROWS = Object.freeze(IDENTITY_ROWS);

export const BUILTIN_MARKER_IDENTITY_DEFINITIONS = Object.freeze(
  BUILTIN_MARKER_IDENTITY_ROWS.map(([identityKey, currentDotKey, legacyDotKeys = [], legacyIdentityKeys = []]) => Object.freeze({
    id: `${BUILTIN_MARKER_ID_PREFIX}${identityKey}`,
    currentDotKey,
    legacyDotKeys: Object.freeze([...legacyDotKeys]),
    legacyIds: Object.freeze(legacyIdentityKeys.map(key => `${BUILTIN_MARKER_ID_PREFIX}${key}`)),
  })),
);
